Repository prgrms-web-devcourse-final-project/WEB5_6_NeogulCoder_BE, pull requests merged in 2025-07, with the labels that each got.

#2 Chore: Java 버전 21로 변경 및 .gitignore 정리
  .gitignore
  build.gradle
  src/main/resources/application.properties
Labels: 🔧 chore

#4 feature: GCP + Docker 기반 배포 환경 구축
  Dockerfile
  build.gradle
  src/main/java/grep/neogul_coder/NeogulCoderApplication.java
Labels: ✨ feature, 🔧 chore

#6 feat: GitHub 이슈와 Jira Task 연동 자동화 설정 추가
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/fix-form.yml
  .github/ISSUE_TEMPLATE/issue-form.yml
  .github/ISSUE_TEMPLATE/✨-feature-template.md
  .github/ISSUE_TEMPLATE/🐛-fix-template.md
  .github/workflows/close-jira-issue.yml
  .github/workflows/create-jira-issue.yml
  .gitignore
Labels: ✨ feature, 🔧 chore

#12 [EA3-76] chore: 깃허브 이슈 라벨 매핑 변경
  .github/ISSUE_TEMPLATE/issue-form.yml
  .github/workflows/create-jira-issue.yml
Labels: 🔧 chore

#19 [EA3-81] feature: 스터디 모집 글, 리뷰 엔티티 작성
  build.gradle
  src/main/java/grep/neogul_coder/NeogulCoderApplication.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/RecruitmentPost.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/RecruitmentPostController.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/RecruitmentPostSpecification.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/request/RecruitmentPostSaveRequest.java
  src/main/java/grep/neogul_coder/domain/review/Review.java
  src/main/java/grep/neogul_coder/domain/review/tag/ReviewMessage.java
  src/main/java/grep/neogul_coder/domain/review/tag/ReviewTag.java
  src/main/java/grep/neogul_coder/domain/review/tag/ReviewTagging.java
  src/main/java/grep/neogul_coder/domain/review/tag/ReviewType.java
  src/main/java/grep/neogul_coder/global/response/ApiResponse.java
  src/main/java/grep/neogul_coder/test/Test.java
Labels: ✨ feature, 🔧 chore

#22 refactor:ApiResponse 변경
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/RecruitmentPostController.java
  src/main/java/grep/neogul_coder/domain/users/controller/UserController.java
  src/main/java/grep/neogul_coder/global/response/ApiResponse.java
Labels: 🐛 fix, ♻️ refactor

#24 [EA3-81] feature: 스터디 모집글 CRUD 스웨거 작성
  build.gradle
  src/main/java/grep/neogul_coder/domain/recruitment/post/RecruitmentPost.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/RecruitmentPostController.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/RecruitmentPostSpecification.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/RecruitmentPostMessage.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/request/RecruitmentPostEditRequest.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/response/RecruitmentPostInfo.java
  src/main/java/grep/neogul_coder/domain/review/tag/ReviewTagging.java
Labels: ✨ feature, 🔧 chore

#30 [EA3-98] feature: 출석 엔티티 작성
  src/main/java/grep/neogul_coder/domain/attendance/Attendance.java
  src/main/java/grep/neogul_coder/domain/attendance/controller/AttendanceController.java
  src/main/java/grep/neogul_coder/domain/attendance/controller/AttendanceSpecification.java
Labels: ✨ feature

#37 [EA3-81] feature: 모집글 상태, 마감일 추가 및 리뷰 주관글 API 명세서 추가
  src/main/java/grep/neogul_coder/domain/recruitment/RecruitmentPostStatus.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/RecruitmentPost.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/RecruitmentPostController.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/RecruitmentPostSpecification.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/request/RecruitmentPostEditRequest.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/request/RecruitmentPostSaveRequest.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/request/RecruitmentPostStatusEditRequest.java
  src/main/java/grep/neogul_coder/domain/review/controller/ReviewController.java
  src/main/java/grep/neogul_coder/domain/review/controller/ReviewSpecification.java
  src/main/java/grep/neogul_coder/domain/review/controller/dto/request/ReviewSaveRequest.java
  src/main/java/grep/neogul_coder/domain/review/controller/dto/response/ReviewPagingContentsInfo.java
Labels: 🐛 fix, ✨ feature, 🔧 chore

#36 [EA3-74] feature : 엔티티 추가
  src/main/java/grep/neogul_coder/domain/calender/entity/PersonalCalender.java
  src/main/java/grep/neogul_coder/domain/calender/entity/TeamCalender.java
Labels: ✨ feature

#48 [EA3-75] feature : 버디 에너지 스웨거 작성 및 패키기 구조 변경
  src/main/java/grep/neogul_coder/domain/buddy/controller/BuddyEnergyController.java
  src/main/java/grep/neogul_coder/domain/buddy/controller/BuddyEnergySpecification.java
  src/main/java/grep/neogul_coder/domain/buddy/controller/dto/response/BuddyEnergyResponse.java
  src/main/java/grep/neogul_coder/domain/buddy/entity/BuddyEnergy.java
  src/main/java/grep/neogul_coder/domain/buddy/entity/BuddyLog.java
  src/main/java/grep/neogul_coder/domain/buddy/enums/BuddyEnergyReason.java
  src/main/java/grep/neogul_coder/domain/calender/controller/PersonalCalenderController.java
  src/main/java/grep/neogul_coder/domain/calender/controller/PersonalCalenderSpecification.java
  src/main/java/grep/neogul_coder/domain/calender/controller/TeamCalenderController.java
  src/main/java/grep/neogul_coder/domain/calender/controller/TeamCalenderSpecification.java
  src/main/java/grep/neogul_coder/domain/calender/controller/dto/requset/PersonalCalenderRequest.java
  src/main/java/grep/neogul_coder/domain/calender/controller/dto/requset/TeamCalenderRequest.java
  src/main/java/grep/neogul_coder/domain/calender/controller/dto/response/PersonalCalenderResponse.java
  src/main/java/grep/neogul_coder/domain/calender/controller/dto/response/TeamCalenderResponse.java
  src/main/java/grep/neogul_coder/domain/groupchat/controller/GroupChatSwaggerController.java
  src/main/java/grep/neogul_coder/domain/groupchat/controller/GroupChatSwaggerSpecification.java
  src/main/java/grep/neogul_coder/domain/groupchat/controller/dto/requset/GroupChatMessageRequestDto.java
  src/main/java/grep/neogul_coder/domain/groupchat/controller/dto/requset/GroupChatSwaggerRequest.java
  src/main/java/grep/neogul_coder/domain/groupchat/controller/dto/response/GroupChatMessageResponseDto.java
  src/main/java/grep/neogul_coder/domain/groupchat/controller/dto/response/GroupChatSwaggerResponse.java
Labels: ✨ feature, ♻️ refactor

#51 [EA3-97] feature: 출석 스웨거 작성
  src/main/java/grep/neogul_coder/domain/attendance/Attendance.java
  src/main/java/grep/neogul_coder/domain/attendance/controller/AttendanceController.java
  src/main/java/grep/neogul_coder/domain/attendance/controller/AttendanceSpecification.java
  src/main/java/grep/neogul_coder/domain/attendance/controller/dto/response/AttendanceResponse.java
Labels: ✨ feature

#50 [EA3-74] refactor: 캘린더 엔티티 수정 / 컨트롤러 리팩토링
  src/main/java/grep/neogul_coder/domain/calender/controller/PersonalCalenderController.java
  src/main/java/grep/neogul_coder/domain/calender/controller/TeamCalenderController.java
  src/main/java/grep/neogul_coder/domain/calender/controller/dto/response/PersonalCalenderResponse.java
  src/main/java/grep/neogul_coder/domain/calender/controller/dto/response/TeamCalenderResponse.java
  src/main/java/grep/neogul_coder/domain/calender/entity/PersonalCalender.java
  src/main/java/grep/neogul_coder/domain/calender/entity/TeamCalender.java
Labels: ♻️ refactor

#58 [EA3-78] feature: 스터디 커뮤니티 게시글 엔티티 및 스웨거 작성(+pageresponse 생성)
  src/main/java/grep/neogul_coder/domain/studypost/Category.java
  src/main/java/grep/neogul_coder/domain/studypost/StudyPost.java
  src/main/java/grep/neogul_coder/domain/studypost/controller/StudyPostController.java
  src/main/java/grep/neogul_coder/domain/studypost/controller/StudyPostSpecification.java
  src/main/java/grep/neogul_coder/domain/studypost/dto/StudyPostDetailResponse.java
  src/main/java/grep/neogul_coder/domain/studypost/dto/StudyPostListResponse.java
  src/main/java/grep/neogul_coder/domain/studypost/dto/StudyPostRequest.java
  src/main/java/grep/neogul_coder/global/response/PageResponse.java
Labels: ✨ feature, 🔧 chore

#59 [EA3-79] feature: 스터디 게시판 댓글 엔티티 및 API 작성
  src/main/java/grep/neogul_coder/domain/comment/Comment.java
  src/main/java/grep/neogul_coder/domain/comment/controller/CommentController.java
  src/main/java/grep/neogul_coder/domain/comment/controller/CommentSpecification.java
  src/main/java/grep/neogul_coder/domain/comment/dto/CommentRequest.java
  src/main/java/grep/neogul_coder/domain/comment/dto/CommentResponse.java
Labels: ✨ feature

#60 [EA3-44] chore: 브랜치 생성 경로 변경
  .github/workflows/create-jira-issue.yml
Labels: 🔧 chore

#57 [EA3-109] feature:Quiz swagger 작성
  src/main/java/grep/neogul_coder/domain/quiz/controller/QuizController.java
  src/main/java/grep/neogul_coder/domain/quiz/controller/QuizSpecification.java
  src/main/java/grep/neogul_coder/domain/quiz/controller/dto/request/QuizRequest.java
  src/main/java/grep/neogul_coder/domain/quiz/controller/dto/response/QuizResponse.java
  src/main/java/grep/neogul_coder/domain/quiz/entity/Quiz.java
Labels: ✨ feature

#52 [EA3-106] feature:PR Template swagger 작성
  src/main/java/grep/neogul_coder/domain/prtemplate/controller/PrTemplateController.java
  src/main/java/grep/neogul_coder/domain/prtemplate/controller/PrTemplateSpecification.java
  src/main/java/grep/neogul_coder/domain/prtemplate/controller/dto/request/IntroductionUpdateRequest.java
  src/main/java/grep/neogul_coder/domain/prtemplate/controller/dto/request/PrUpdateRequest.java
  src/main/java/grep/neogul_coder/domain/prtemplate/controller/dto/response/PrPageResponse.java
  src/main/java/grep/neogul_coder/domain/prtemplate/entity/Link.java
  src/main/java/grep/neogul_coder/domain/prtemplate/entity/PrTemplate.java
  src/main/java/grep/neogul_coder/domain/users/controller/UserController.java
  src/main/java/grep/neogul_coder/domain/users/controller/UserSpecification.java
  src/main/java/grep/neogul_coder/domain/users/controller/dto/request/PasswordRequest.java
  src/main/java/grep/neogul_coder/domain/users/controller/dto/request/SignUpRequest.java
  src/main/java/grep/neogul_coder/domain/users/controller/dto/request/UpdatePasswordRequest.java
  src/main/java/grep/neogul_coder/domain/users/controller/dto/request/UpdateProfileRequest.java
  src/main/java/grep/neogul_coder/domain/users/controller/dto/response/UserResponse.java
  src/main/java/grep/neogul_coder/domain/users/service/UserService.java
  src/main/java/grep/neogul_coder/global/auth/controller/AuthController.java
  src/main/java/grep/neogul_coder/global/auth/payload/LoginRequest.java
  src/main/java/grep/neogul_coder/global/config/WebSocketConfig.java
  src/main/java/grep/neogul_coder/global/config/security/SecurityConfig.java
Labels: ✨ feature

#61 [EA3-77] refactor: 엔드포인트 변경 및 Response 필드 추가
  src/main/java/grep/neogul_coder/domain/study/controller/StudyManagementController.java
  src/main/java/grep/neogul_coder/domain/study/controller/dto/response/StudyResponse.java
Labels: ♻️ refactor

#62 [EA3-108] Feature: 모집글 수정 삭제 구현 및 테스트 추가
  .gitignore
  src/main/java/grep/neogul_coder/domain/recruitment/RecruitmentErrorCode.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/RecruitmentPost.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/RecruitmentPostController.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/RecruitmentPostSpecification.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/request/RecruitmentPostCreateRequest.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/request/RecruitmentPostEditRequest.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/request/RecruitmentPostSaveRequest.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/request/RecruitmentPostStatusEditRequest.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/request/RecruitmentPostStatusUpdateRequest.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/request/RecruitmentPostUpdateRequest.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/response/ParticipatedStudyInfo.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/response/ParticipatedStudyNamesInfo.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/response/RecruitmentApplicationPagingInfo.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/response/RecruitmentPostCommentPagingInfo.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/response/RecruitmentPostInfo.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/repository/RecruitmentPostRepository.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/service/RecruitmentPostService.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/service/request/RecruitmentPostCreateServiceRequest.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/service/request/RecruitmentPostStatusUpdateServiceRequest.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/service/request/RecruitmentPostUpdateServiceRequest.java
  src/main/java/grep/neogul_coder/domain/studyapplication/controller/dto/response/ApplicationResponse.java
  src/main/java/grep/neogul_coder/global/auth/Principal.java
  src/main/java/grep/neogul_coder/global/auth/jwt/JwtTokenProvider.java
  src/main/java/grep/neogul_coder/global/exception/business/BusinessException.java
  src/main/java/grep/neogul_coder/global/exception/business/NotFoundException.java
  src/test/java/grep/neogul_coder/domain/recruitment/post/service/RecruitmentPostServiceTest.java
Labels: 🐛 fix, ✨ feature, 🔧 chore

#64 [EA3-80] feature: 스터디 최적 시간 투표 관련 엔티티 및 스웨거 작성
  src/main/java/grep/neogul_coder/domain/timevote/controller/TimeVoteController.java
  src/main/java/grep/neogul_coder/domain/timevote/controller/TimeVoteSpecification.java
  src/main/java/grep/neogul_coder/domain/timevote/dto/request/TimeVoteBulkCreateRequest.java
  src/main/java/grep/neogul_coder/domain/timevote/dto/request/TimeVoteBulkDeleteRequest.java
  src/main/java/grep/neogul_coder/domain/timevote/dto/request/TimeVoteBulkUpdateRequest.java
  src/main/java/grep/neogul_coder/domain/timevote/dto/request/TimeVoteCreateRequest.java
  src/main/java/grep/neogul_coder/domain/timevote/dto/request/TimeVoteDeleteRequest.java
  src/main/java/grep/neogul_coder/domain/timevote/dto/request/TimeVotePeriodCreateRequest.java
  src/main/java/grep/neogul_coder/domain/timevote/dto/request/TimeVoteUpdateRequest.java
  src/main/java/grep/neogul_coder/domain/timevote/dto/response/TimeVotePeriodResponse.java
  src/main/java/grep/neogul_coder/domain/timevote/dto/response/TimeVoteResponse.java
  src/main/java/grep/neogul_coder/domain/timevote/dto/response/TimeVoteStatResponse.java
  src/main/java/grep/neogul_coder/domain/timevote/entity/TimeVote.java
  src/main/java/grep/neogul_coder/domain/timevote/entity/TimeVotePeriod.java
  src/main/java/grep/neogul_coder/domain/timevote/entity/TimeVoteStat.java
Labels: ✨ feature

#68 [EA3-44] chore : 기존 이슈 템플릿 삭제
  .github/ISSUE_TEMPLATE/✨-feature-template.md
  .github/ISSUE_TEMPLATE/🐛-fix-template.md
Labels: 🔧 chore

#72 [EA3-118] Feature: 리뷰 대상 회원 조회 API 추가 및 리뷰 도메인 수정
  src/main/java/grep/neogul_coder/domain/review/BadReviewTag.java
  src/main/java/grep/neogul_coder/domain/review/ExcellentReviewTag.java
  src/main/java/grep/neogul_coder/domain/review/GoodReviewTag.java
  src/main/java/grep/neogul_coder/domain/review/Review.java
  src/main/java/grep/neogul_coder/domain/review/ReviewTag.java
  src/main/java/grep/neogul_coder/domain/review/ReviewTagFinder.java
  src/main/java/grep/neogul_coder/domain/review/ReviewTags.java
  src/main/java/grep/neogul_coder/domain/review/ReviewType.java
  src/main/java/grep/neogul_coder/domain/review/controller/ReviewController.java
  src/main/java/grep/neogul_coder/domain/review/controller/ReviewSpecification.java
  src/main/java/grep/neogul_coder/domain/review/controller/dto/response/ReviewTargetUsersInfo.java
  src/main/java/grep/neogul_coder/domain/review/entity/MyReviewTagEntity.java
  src/main/java/grep/neogul_coder/domain/review/entity/ReviewEntity.java
  src/main/java/grep/neogul_coder/domain/review/entity/ReviewTagEntity.java
  src/main/java/grep/neogul_coder/domain/review/entity/ReviewTaggingEntity.java
  src/main/java/grep/neogul_coder/domain/study/StudyMember.java
  src/main/java/grep/neogul_coder/domain/users/entity/User.java
  src/main/java/grep/neogul_coder/global/auth/jwt/JwtTokenProvider.java
  src/test/java/grep/neogul_coder/domain/review/ReviewTagFinderTest.java
  src/test/java/grep/neogul_coder/domain/review/ReviewTagsTest.java
Labels: 🐛 fix, ✨ feature

#75 [EA3-118] Feature: 리뷰 대상 조회 및 생성 구현
  src/main/java/grep/neogul_coder/domain/review/ReviewErrorCode.java
  src/main/java/grep/neogul_coder/domain/review/controller/ReviewController.java
  src/main/java/grep/neogul_coder/domain/review/controller/dto/request/ReviewSaveRequest.java
  src/main/java/grep/neogul_coder/domain/review/controller/service/ReviewService.java
  src/main/java/grep/neogul_coder/domain/review/controller/service/request/ReviewSaveServiceRequest.java
  src/main/java/grep/neogul_coder/domain/review/repository/ReviewQueryRepository.java
  src/main/java/grep/neogul_coder/domain/review/repository/ReviewRepository.java
  src/main/java/grep/neogul_coder/domain/study/Study.java
  src/main/java/grep/neogul_coder/domain/study/repository/StudyMemberRepository.java
  src/main/java/grep/neogul_coder/domain/users/repository/UserRepository.java
Labels: ✨ feature, ♻️ refactor

#73 [EA3-123] Feature: 회원 예외에 관한 로직 추가
  src/main/java/grep/neogul_coder/domain/recruitment/RecruitmentErrorCode.java
  src/main/java/grep/neogul_coder/domain/users/exception/PasswordNotMatchException.java
  src/main/java/grep/neogul_coder/domain/users/exception/PasswordUncheckException.java
  src/main/java/grep/neogul_coder/domain/users/exception/advice/UserAdvice.java
  src/main/java/grep/neogul_coder/domain/users/exception/code/UserErrorCode.java
  src/main/java/grep/neogul_coder/domain/users/service/UserService.java
  src/main/java/grep/neogul_coder/global/auth/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/grep/neogul_coder/global/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/grep/neogul_coder/global/auth/jwt/JwtExceptionFilter.java
  src/main/java/grep/neogul_coder/global/auth/jwt/TokenCookieFactory.java
  src/main/java/grep/neogul_coder/global/auth/service/AuthService.java
  src/main/java/grep/neogul_coder/global/code/Code.java
  src/main/java/grep/neogul_coder/global/code/CommonCode.java
  src/main/java/grep/neogul_coder/global/code/ErrorCode.java
  src/main/java/grep/neogul_coder/global/exception/AuthApiException.java
  src/main/java/grep/neogul_coder/global/exception/AuthWebException.java
  src/main/java/grep/neogul_coder/global/exception/CommonException.java
  src/main/java/grep/neogul_coder/global/exception/GoogleUserLoginException.java
  src/main/java/grep/neogul_coder/global/exception/advice/AuthExceptionAdvice.java
  src/main/java/grep/neogul_coder/global/exception/business/BusinessException.java
  src/main/java/grep/neogul_coder/global/exception/business/NotFoundException.java
  src/main/java/grep/neogul_coder/global/exception/validation/DuplicatedException.java
  src/main/java/grep/neogul_coder/global/exception/validation/ValidationException.java
  src/main/java/grep/neogul_coder/global/response/ApiResponse.java
Labels: ✨ feature

#78 [EA3-118] Feature: 리뷰 대상 조회시 스터디 이름, 이미지 추가 및 코드 리팩토링
  src/main/java/grep/neogul_coder/domain/review/ReviewErrorCode.java
  src/main/java/grep/neogul_coder/domain/review/ReviewTags.java
  src/main/java/grep/neogul_coder/domain/review/controller/dto/response/ReviewTargetUsersInfo.java
  src/main/java/grep/neogul_coder/domain/review/controller/service/ReviewService.java
  src/main/java/grep/neogul_coder/domain/study/Study.java
  src/main/java/grep/neogul_coder/domain/study/repository/StudyMemberRepository.java
  src/test/java/grep/neogul_coder/domain/review/ReviewTagsTest.java
Labels: ✨ feature, ♻️ refactor

#81 [EA3-122] feature: 스터디 목록 조회, 생성 기능 구현
  src/main/java/grep/neogul_coder/domain/study/Study.java
  src/main/java/grep/neogul_coder/domain/study/StudyMember.java
  src/main/java/grep/neogul_coder/domain/study/controller/StudyController.java
  src/main/java/grep/neogul_coder/domain/study/controller/StudySpecification.java
  src/main/java/grep/neogul_coder/domain/study/controller/dto/request/StudyCreateRequest.java
  src/main/java/grep/neogul_coder/domain/study/controller/dto/response/StudyItemResponse.java
  src/main/java/grep/neogul_coder/domain/study/repository/StudyMemberRepository.java
  src/main/java/grep/neogul_coder/domain/study/repository/StudyRepository.java
  src/main/java/grep/neogul_coder/domain/study/service/StudyService.java
  src/main/java/grep/neogul_coder/domain/users/repository/UserRepository.java
Labels: ✨ feature

#80 [EA3-74] feature: 캘린더 날짜별 리스트 형식의 일정 상세조회 api 추가 및 리팩토링 + 엔티티 내 nullable 제거
  src/main/java/grep/neogul_coder/domain/buddy/entity/BuddyEnergy.java
  src/main/java/grep/neogul_coder/domain/calender/controller/PersonalCalenderController.java
  src/main/java/grep/neogul_coder/domain/calender/controller/PersonalCalenderSpecification.java
  src/main/java/grep/neogul_coder/domain/calender/controller/TeamCalenderController.java
  src/main/java/grep/neogul_coder/domain/calender/controller/TeamCalenderSpecification.java
  src/main/java/grep/neogul_coder/domain/calender/entity/Calender.java
  src/main/java/grep/neogul_coder/domain/calender/entity/PersonalCalender.java
  src/main/java/grep/neogul_coder/domain/calender/entity/TeamCalender.java
  src/main/java/grep/neogul_coder/domain/groupchat/entity/GroupChatMessage.java
  src/main/java/grep/neogul_coder/domain/groupchat/entity/GroupChatRoom.java
Labels: ✨ feature, ♻️ refactor

#83 [EA3-118] Feature: 나의 리뷰 태그들 조회 구현 및 리뷰 API 테스트
  src/main/java/grep/neogul_coder/domain/review/ReviewTags.java
  src/main/java/grep/neogul_coder/domain/review/controller/ReviewController.java
  src/main/java/grep/neogul_coder/domain/review/controller/ReviewSpecification.java
  src/main/java/grep/neogul_coder/domain/review/controller/dto/response/MyReviewTagsInfo.java
  src/main/java/grep/neogul_coder/domain/review/controller/dto/response/ReviewTagsInfo.java
  src/main/java/grep/neogul_coder/domain/review/controller/dto/response/ReviewTargetUsersInfo.java
  src/main/java/grep/neogul_coder/domain/review/controller/service/ReviewService.java
  src/main/java/grep/neogul_coder/domain/review/entity/MyReviewTagEntity.java
  src/main/java/grep/neogul_coder/domain/review/entity/ReviewEntity.java
  src/main/java/grep/neogul_coder/domain/review/entity/ReviewTagEntity.java
  src/main/java/grep/neogul_coder/domain/review/repository/MyReviewTagRepository.java
  src/main/java/grep/neogul_coder/domain/review/repository/ReviewTagRepository.java
  src/main/java/grep/neogul_coder/global/init/ReviewTagInitializer.java
  src/test/java/grep/neogul_coder/domain/review/controller/service/ReviewServiceTest.java
Labels: ✨ feature, ♻️ refactor

#88 [EA3-132] Feature: 모집글 페이징 API 추가
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/RecruitmentPostController.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/RecruitmentPostSaveController.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/RecruitmentPostSaveSpecification.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/RecruitmentPostSpecification.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/response/RecruitmentPagingInfo.java
  src/main/java/grep/neogul_coder/domain/review/controller/ReviewController.java
  src/main/java/grep/neogul_coder/domain/review/controller/ReviewSpecification.java
  src/main/java/grep/neogul_coder/domain/review/controller/dto/request/ReviewSaveRequest.java
  src/main/java/grep/neogul_coder/domain/review/controller/dto/response/MyReviewTagsInfo.java
  src/main/java/grep/neogul_coder/domain/review/controller/dto/response/ReviewContentsPagingInfo.java
  src/main/java/grep/neogul_coder/domain/review/controller/dto/response/ReviewPagingContentsInfo.java
  src/main/java/grep/neogul_coder/domain/review/controller/dto/response/ReviewTargetUsersInfo.java
  src/main/java/grep/neogul_coder/domain/review/entity/MyReviewTagEntity.java
  src/main/java/grep/neogul_coder/domain/review/entity/ReviewEntity.java
  src/main/java/grep/neogul_coder/domain/review/entity/ReviewTagEntity.java
  src/main/java/grep/neogul_coder/domain/review/repository/ReviewQueryRepository.java
  src/main/java/grep/neogul_coder/domain/review/service/ReviewService.java
  src/main/java/grep/neogul_coder/domain/review/service/request/ReviewSaveServiceRequest.java
  src/main/java/grep/neogul_coder/global/entity/BaseEntity.java
  src/test/java/grep/neogul_coder/NeogulCoderApplicationTests.java
  src/test/java/grep/neogul_coder/domain/IntegrationTestSupport.java
  src/test/java/grep/neogul_coder/domain/recruitment/post/service/RecruitmentPostServiceTest.java
  src/test/java/grep/neogul_coder/domain/review/controller/service/ReviewServiceTest.java
  src/test/java/grep/neogul_coder/domain/review/repository/ReviewQueryRepositoryTest.java
Labels: ✨ feature

#94 [EA3-134] refactor : 최적 시간 투표 관련 엔티티 GenerationType.IDENTITY로 변경
  src/main/java/grep/neogul_coder/domain/timevote/entity/TimeVote.java
  src/main/java/grep/neogul_coder/domain/timevote/entity/TimeVotePeriod.java
  src/main/java/grep/neogul_coder/domain/timevote/entity/TimeVoteStat.java
Labels: ♻️ refactor

#97 [EA3-132] Feature: 모집글 삭제 상태 제거및 EnumType 추가
  src/main/java/grep/neogul_coder/domain/comment/Comment.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/RecruitmentPost.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/service/RecruitmentPostService.java
  src/main/java/grep/neogul_coder/domain/studypost/StudyPost.java
Labels: ✨ feature

#95 [EA3] refactor : h2-console 접근 위해 headers.disable() 추가
  src/main/java/grep/neogul_coder/global/config/security/SecurityConfig.java
Labels: ♻️ refactor

#98 [EA3] chore : 목업데이터 파일 추가
  src/main/resources/import.sql
Labels: 🔧 chore

#103 [EA3] chore: develop → main 브랜치 머지
  src/main/java/grep/neogul_coder/domain/quiz/entity/Quiz.java
Labels: 🔧 chore

#107 [EA3-132] feature: 리뷰 기능 예외 추가 및 수정
  src/main/java/grep/neogul_coder/domain/review/ReviewErrorCode.java
  src/main/java/grep/neogul_coder/domain/review/controller/dto/request/ReviewSaveRequest.java
  src/main/java/grep/neogul_coder/domain/review/repository/ReviewQueryRepository.java
  src/main/java/grep/neogul_coder/domain/review/repository/ReviewRepository.java
  src/main/java/grep/neogul_coder/domain/review/service/ReviewService.java
  src/main/java/grep/neogul_coder/global/init/ReviewTagInitializer.java
Labels: ✨ feature

#105 [EA3-136] Fix: PR 템플릿 에러 수정
  src/main/java/grep/neogul_coder/domain/prtemplate/controller/dto/request/LinkUpdateRequest.java
  src/main/java/grep/neogul_coder/domain/prtemplate/controller/dto/request/PrUpdateRequest.java
  src/main/java/grep/neogul_coder/domain/prtemplate/repository/LinkRepository.java
  src/main/java/grep/neogul_coder/domain/prtemplate/service/LinkService.java
  src/main/java/grep/neogul_coder/domain/prtemplate/service/PrTemplateService.java
  src/main/resources/import.sql
Labels: 🐛 fix

#108 chore: develop → main 브랜치 머지
  src/main/java/grep/neogul_coder/domain/prtemplate/controller/dto/request/LinkUpdateRequest.java
  src/main/java/grep/neogul_coder/domain/prtemplate/controller/dto/request/PrUpdateRequest.java
  src/main/java/grep/neogul_coder/domain/prtemplate/repository/LinkRepository.java
  src/main/java/grep/neogul_coder/domain/prtemplate/service/LinkService.java
  src/main/java/grep/neogul_coder/domain/prtemplate/service/PrTemplateService.java
  src/main/java/grep/neogul_coder/domain/review/ReviewErrorCode.java
  src/main/java/grep/neogul_coder/domain/review/controller/dto/request/ReviewSaveRequest.java
  src/main/java/grep/neogul_coder/domain/review/repository/ReviewQueryRepository.java
  src/main/java/grep/neogul_coder/domain/review/repository/ReviewRepository.java
  src/main/java/grep/neogul_coder/domain/review/service/ReviewService.java
  src/main/java/grep/neogul_coder/domain/study/controller/StudyController.java
  src/main/java/grep/neogul_coder/domain/study/controller/StudySpecification.java
  src/main/java/grep/neogul_coder/domain/study/controller/dto/request/StudyCreateRequest.java
  src/main/java/grep/neogul_coder/domain/study/controller/dto/response/StudyHeaderResponse.java
  src/main/java/grep/neogul_coder/domain/study/controller/dto/response/StudyImageResponse.java
  src/main/java/grep/neogul_coder/domain/study/controller/dto/response/StudyInfoResponse.java
  src/main/java/grep/neogul_coder/domain/study/controller/dto/response/StudyItemResponse.java
  src/main/java/grep/neogul_coder/domain/study/controller/dto/response/StudyMemberResponse.java
  src/main/java/grep/neogul_coder/domain/study/exception/NotStudyLeaderException.java
  src/main/java/grep/neogul_coder/domain/study/exception/code/StudyErrorCode.java
  src/main/java/grep/neogul_coder/domain/study/repository/StudyQueryRepository.java
  src/main/java/grep/neogul_coder/domain/study/repository/StudyRepository.java
  src/main/java/grep/neogul_coder/domain/study/service/StudyService.java
  src/main/java/grep/neogul_coder/domain/users/repository/UserRepository.java
  src/main/java/grep/neogul_coder/global/config/QuerydslConfig.java
  src/main/java/grep/neogul_coder/global/exception/advice/WebExceptionAdvice.java
  src/main/java/grep/neogul_coder/global/exception/business/BusinessException.java
  src/main/java/grep/neogul_coder/global/init/ReviewTagInitializer.java
  src/main/resources/import.sql
Labels: 🔧 chore

#111 [EA3-137] 회원 기능을 회원 인증 정보를 통해 하도록 변경
  src/main/java/grep/neogul_coder/domain/prtemplate/exception/TemplateNotFoundException.java
  src/main/java/grep/neogul_coder/domain/prtemplate/exception/advice/PrTemplateAdvice.java
  src/main/java/grep/neogul_coder/domain/prtemplate/repository/PrTemplateRepository.java
  src/main/java/grep/neogul_coder/domain/prtemplate/service/LinkService.java
  src/main/java/grep/neogul_coder/domain/prtemplate/service/PrTemplateService.java
  src/main/java/grep/neogul_coder/domain/users/controller/UserController.java
  src/main/java/grep/neogul_coder/domain/users/controller/UserSpecification.java
  src/main/java/grep/neogul_coder/domain/users/controller/dto/response/UserResponse.java
  src/main/java/grep/neogul_coder/domain/users/exception/EmailDuplicationException.java
  src/main/java/grep/neogul_coder/domain/users/exception/NicknameDuplicatedException.java
  src/main/java/grep/neogul_coder/domain/users/exception/UserNotFoundException.java
  src/main/java/grep/neogul_coder/domain/users/exception/advice/UserAdvice.java
  src/main/java/grep/neogul_coder/domain/users/exception/code/UserErrorCode.java
  src/main/java/grep/neogul_coder/domain/users/service/UserService.java
  src/main/java/grep/neogul_coder/global/auth/Principal.java
  src/main/java/grep/neogul_coder/global/auth/controller/AuthController.java
  src/main/java/grep/neogul_coder/global/auth/oauth/CustomAuthorizationRequestResolver.java
  src/main/java/grep/neogul_coder/global/config/WebSocketConfig.java
  src/main/java/grep/neogul_coder/global/config/security/SecurityConfig.java
Labels: ✨ feature

#113 [EA3-138] Feature: 참여 중인 스터디 정보 조회 및 스터디 불러오기 구현
  src/main/java/grep/neogul_coder/domain/recruitment/RecruitmentErrorCode.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/RecruitmentPost.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/RecruitmentPostSaveController.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/RecruitmentPostSaveSpecification.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/request/RecruitmentPostCreateRequest.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/response/JoinedStudiesInfo.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/response/JoinedStudyLoadInfo.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/response/ParticipatedStudyInfo.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/response/ParticipatedStudyNamesInfo.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/repository/RecruitmentPostRepository.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/service/RecruitmentPostSaveService.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/service/RecruitmentPostService.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/service/request/RecruitmentPostCreateServiceRequest.java
  src/main/java/grep/neogul_coder/domain/study/Study.java
  src/main/java/grep/neogul_coder/domain/study/StudyMember.java
  src/main/java/grep/neogul_coder/domain/study/repository/StudyMemberQueryRepository.java
  src/main/java/grep/neogul_coder/domain/study/repository/StudyQueryRepository.java
  src/test/java/grep/neogul_coder/domain/recruitment/post/service/RecruitmentPostSaveServiceTest.java
  src/test/java/grep/neogul_coder/domain/recruitment/post/service/RecruitmentPostServiceTest.java
  src/test/java/grep/neogul_coder/domain/study/repository/StudyMemberQueryRepositoryTest.java
Labels: ✨ feature, ♻️ refactor

#116 [EA3-122] feature: 스터디 수정, 삭제 및 테스트 코드 작성
  gradlew.bat
  src/main/java/grep/neogul_coder/domain/recruitment/post/repository/RecruitmentPostRepository.java
  src/main/java/grep/neogul_coder/domain/study/Study.java
  src/main/java/grep/neogul_coder/domain/study/controller/StudyController.java
  src/main/java/grep/neogul_coder/domain/study/controller/StudySpecification.java
  src/main/java/grep/neogul_coder/domain/study/controller/dto/request/StudyCreateRequest.java
  src/main/java/grep/neogul_coder/domain/study/controller/dto/request/StudyUpdateRequest.java
  src/main/java/grep/neogul_coder/domain/study/controller/dto/response/StudyItemPagingResponse.java
  src/main/java/grep/neogul_coder/domain/study/controller/dto/response/StudyMyInfoResponse.java
  src/main/java/grep/neogul_coder/domain/study/controller/dto/response/StudyResponse.java
  src/main/java/grep/neogul_coder/domain/study/exception/NotStudyLeaderException.java
  src/main/java/grep/neogul_coder/domain/study/exception/code/StudyErrorCode.java
  src/main/java/grep/neogul_coder/domain/study/repository/StudyMemberRepository.java
  src/main/java/grep/neogul_coder/domain/study/repository/StudyQueryRepository.java
  src/main/java/grep/neogul_coder/domain/study/repository/StudyRepository.java
  src/main/java/grep/neogul_coder/domain/study/service/StudyService.java
  src/test/java/grep/neogul_coder/domain/study/service/StudyServiceTest.java
Labels: ✨ feature, ♻️ refactor

#118 chore: develop → main 브랜치 머지
  gradlew.bat
  src/main/java/grep/neogul_coder/domain/recruitment/comment/RecruitmentPostComment.java
  src/main/java/grep/neogul_coder/domain/recruitment/comment/controller/RecruitmentPostCommentController.java
  src/main/java/grep/neogul_coder/domain/recruitment/comment/controller/RecruitmentPostCommentSpecification.java
  src/main/java/grep/neogul_coder/domain/recruitment/comment/controller/dto/request/RecruitmentCommentSaveRequest.java
  src/main/java/grep/neogul_coder/domain/recruitment/comment/controller/dto/request/RecruitmentCommentUpdateRequest.java
  src/main/java/grep/neogul_coder/domain/recruitment/comment/repository/RecruitmentPostCommentQueryRepository.java
  src/main/java/grep/neogul_coder/domain/recruitment/comment/repository/RecruitmentPostCommentRepository.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/RecruitmentPostSaveController.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/RecruitmentPostSaveSpecification.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/request/save/RecruitmentPostCreateRequest.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/response/RecruitmentPostPagingInfo.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/response/save/JoinedStudiesInfo.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/response/save/JoinedStudyLoadInfo.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/repository/RecruitmentPostRepository.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/service/RecruitmentPostSaveService.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/service/RecruitmentPostService.java
  src/main/java/grep/neogul_coder/domain/review/controller/ReviewController.java
  src/main/java/grep/neogul_coder/domain/review/controller/ReviewSpecification.java
  src/main/java/grep/neogul_coder/domain/review/controller/dto/response/JoinedStudiesInfo.java
  src/main/java/grep/neogul_coder/domain/review/controller/dto/response/ReviewTargetUsersInfo.java
  src/main/java/grep/neogul_coder/domain/review/service/ReviewService.java
  src/main/java/grep/neogul_coder/domain/study/Study.java
  src/main/java/grep/neogul_coder/domain/study/controller/StudyController.java
  src/main/java/grep/neogul_coder/domain/study/controller/StudySpecification.java
  src/main/java/grep/neogul_coder/domain/study/controller/dto/request/StudyCreateRequest.java
  src/main/java/grep/neogul_coder/domain/study/controller/dto/request/StudyUpdateRequest.java
  src/main/java/grep/neogul_coder/domain/study/controller/dto/response/StudyItemPagingResponse.java
  src/main/java/grep/neogul_coder/domain/study/controller/dto/response/StudyMyInfoResponse.java
  src/main/java/grep/neogul_coder/domain/study/controller/dto/response/StudyResponse.java
  src/main/java/grep/neogul_coder/domain/study/exception/NotStudyLeaderException.java
  src/main/java/grep/neogul_coder/domain/study/exception/code/StudyErrorCode.java
  src/main/java/grep/neogul_coder/domain/study/repository/StudyMemberRepository.java
  src/main/java/grep/neogul_coder/domain/study/repository/StudyQueryRepository.java
  src/main/java/grep/neogul_coder/domain/study/repository/StudyRepository.java
  src/main/java/grep/neogul_coder/domain/study/service/StudyService.java
  src/test/java/grep/neogul_coder/domain/recruitment/post/repository/RecruitmentPostCommentQueryRepositoryTest.java
  src/test/java/grep/neogul_coder/domain/recruitment/post/service/RecruitmentPostSaveServiceTest.java
  src/test/java/grep/neogul_coder/domain/recruitment/post/service/RecruitmentPostServiceTest.java
  src/test/java/grep/neogul_coder/domain/review/controller/service/ReviewServiceTest.java
  src/test/java/grep/neogul_coder/domain/study/service/StudyServiceTest.java
Labels: 🔧 chore

#119 [EA3-138] feature: 모집글 페이징 조회 기능 추가 및 깃 충돌 해결
  src/main/java/grep/neogul_coder/domain/recruitment/comment/repository/RecruitmentPostCommentQueryRepository.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/RecruitmentPostController.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/RecruitmentPostSpecification.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/response/RecruitmentPagingInfo.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/repository/RecruitmentPostQueryRepository.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/service/RecruitmentPostService.java
  src/main/java/grep/neogul_coder/domain/study/repository/StudyRepository.java
  src/test/java/grep/neogul_coder/domain/recruitment/post/service/RecruitmentPostServiceTest.java
Labels: 🐛 fix, ✨ feature

#120 chore: develop → main 브랜치 머지
  src/main/java/grep/neogul_coder/domain/recruitment/comment/repository/RecruitmentPostCommentQueryRepository.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/RecruitmentPostController.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/RecruitmentPostSpecification.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/response/RecruitmentPagingInfo.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/repository/RecruitmentPostQueryRepository.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/service/RecruitmentPostService.java
  src/main/java/grep/neogul_coder/domain/study/repository/StudyRepository.java
  src/test/java/grep/neogul_coder/domain/recruitment/post/service/RecruitmentPostServiceTest.java
Labels: 🔧 chore

#121 [EA3-143] Ai 퀴즈 생성 및 DB에 저장 로직
  build.gradle
  src/main/java/grep/neogul_coder/domain/prtemplate/controller/PrTemplateController.java
  src/main/java/grep/neogul_coder/domain/prtemplate/controller/PrTemplateSpecification.java
  src/main/java/grep/neogul_coder/domain/prtemplate/entity/Link.java
  src/main/java/grep/neogul_coder/domain/prtemplate/repository/LinkRepository.java
  src/main/java/grep/neogul_coder/domain/prtemplate/service/LinkService.java
  src/main/java/grep/neogul_coder/domain/prtemplate/service/PrTemplateService.java
  src/main/java/grep/neogul_coder/domain/quiz/controller/AiQuizController.java
  src/main/java/grep/neogul_coder/domain/quiz/controller/AiQuizSpecification.java
  src/main/java/grep/neogul_coder/domain/quiz/controller/QuizController.java
  src/main/java/grep/neogul_coder/domain/quiz/controller/dto/request/QuizRequest.java
  src/main/java/grep/neogul_coder/domain/quiz/controller/dto/response/QuizResponse.java
  src/main/java/grep/neogul_coder/domain/quiz/entity/Quiz.java
  src/main/java/grep/neogul_coder/domain/quiz/exception/PostNotFreeException.java
  src/main/java/grep/neogul_coder/domain/quiz/exception/QuizNotFoundException.java
  src/main/java/grep/neogul_coder/domain/quiz/exception/advice/QuizAdvice.java
  src/main/java/grep/neogul_coder/domain/quiz/exception/code/QuizErrorCode.java
  src/main/java/grep/neogul_coder/domain/quiz/repository/AiQuizRepository.java
  src/main/java/grep/neogul_coder/domain/quiz/service/AiQuizService.java
  src/main/java/grep/neogul_coder/domain/quiz/service/AiQuizServiceImpl.java
  src/main/java/grep/neogul_coder/domain/studypost/StudyPost.java
  src/main/java/grep/neogul_coder/domain/studypost/exception/PostNotFoundException.java
  src/main/java/grep/neogul_coder/domain/studypost/exception/advice/PostAdvice.java
  src/main/java/grep/neogul_coder/domain/studypost/exception/code/PostErrorCode.java
  src/main/java/grep/neogul_coder/domain/studypost/repository/StudyPostRepository.java
  src/main/java/grep/neogul_coder/domain/studypost/service/StudyPostService.java
  src/main/java/grep/neogul_coder/domain/users/controller/UserController.java
  src/main/java/grep/neogul_coder/domain/users/controller/dto/request/UpdatePasswordRequest.java
  src/main/java/grep/neogul_coder/domain/users/controller/dto/response/UserResponse.java
  src/main/java/grep/neogul_coder/domain/users/service/UserService.java
Labels: ✨ feature

#122 [EA3-138] feature: 모집글 조회 기능 구현
  src/main/java/grep/neogul_coder/domain/recruitment/comment/controller/dto/response/CommentsWithWriterInfo.java
  src/main/java/grep/neogul_coder/domain/recruitment/comment/repository/RecruitmentPostCommentQueryRepository.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/RecruitmentPostController.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/RecruitmentPostSaveController.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/RecruitmentPostSaveSpecification.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/RecruitmentPostSpecification.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/request/RecruitmentPostStatusUpdateRequest.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/request/RecruitmentPostUpdateRequest.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/response/RecruitmentPostDetailsInfo.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/response/RecruitmentPostInfo.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/response/RecruitmentPostPagingInfo.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/repository/RecruitmentPostQueryRepository.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/service/RecruitmentPostService.java
  src/main/java/grep/neogul_coder/domain/review/controller/ReviewController.java
  src/main/java/grep/neogul_coder/domain/review/controller/ReviewSpecification.java
  src/main/java/grep/neogul_coder/domain/review/service/ReviewService.java
  src/main/java/grep/neogul_coder/domain/studyapplication/ApplicationStatus.java
  src/main/java/grep/neogul_coder/domain/studyapplication/StudyApplication.java
  src/main/java/grep/neogul_coder/domain/studyapplication/repository/StudyApplicationRepository.java
  src/main/java/grep/neogul_coder/domain/users/entity/User.java
  src/main/java/grep/neogul_coder/global/auth/service/AuthService.java
  src/main/resources/data.sql
  src/test/java/grep/neogul_coder/domain/recruitment/post/repository/RecruitmentPostCommentQueryRepositoryTest.java
  src/test/java/grep/neogul_coder/domain/recruitment/post/repository/RecruitmentPostQueryRepositoryTest.java
  src/test/java/grep/neogul_coder/domain/recruitment/post/service/RecruitmentPostServiceTest.java
Labels: ✨ feature

#123 [EA3-112] feature : 캘린더 기능 구현 및 예외처리
  src/main/java/grep/neogul_coder/domain/calender/controller/PersonalCalendarController.java
  src/main/java/grep/neogul_coder/domain/calender/controller/PersonalCalendarSpecification.java
  src/main/java/grep/neogul_coder/domain/calender/controller/TeamCalendarController.java
  src/main/java/grep/neogul_coder/domain/calender/controller/TeamCalendarSpecification.java
  src/main/java/grep/neogul_coder/domain/calender/controller/dto/requset/PersonalCalendarRequest.java
  src/main/java/grep/neogul_coder/domain/calender/controller/dto/requset/TeamCalendarRequest.java
  src/main/java/grep/neogul_coder/domain/calender/controller/dto/response/PersonalCalendarResponse.java
  src/main/java/grep/neogul_coder/domain/calender/controller/dto/response/TeamCalendarResponse.java
  src/main/java/grep/neogul_coder/domain/calender/entity/Calendar.java
  src/main/java/grep/neogul_coder/domain/calender/entity/PersonalCalendar.java
  src/main/java/grep/neogul_coder/domain/calender/entity/TeamCalendar.java
  src/main/java/grep/neogul_coder/domain/calender/exception/CalendarNotFoundException.java
  src/main/java/grep/neogul_coder/domain/calender/exception/CalendarValidationException.java
  src/main/java/grep/neogul_coder/domain/calender/exception/code/CalendarErrorCode.java
  src/main/java/grep/neogul_coder/domain/calender/repository/PersonalCalendarQueryRepository.java
  src/main/java/grep/neogul_coder/domain/calender/repository/PersonalCalendarRepository.java
  src/main/java/grep/neogul_coder/domain/calender/repository/TeamCalendarQueryRepository.java
  src/main/java/grep/neogul_coder/domain/calender/repository/TeamCalendarRepository.java
  src/main/java/grep/neogul_coder/domain/calender/service/PersonalCalendarService.java
  src/main/java/grep/neogul_coder/domain/calender/service/TeamCalendarService.java
  src/main/resources/data.sql
Labels: ✨ feature, ♻️ refactor

#134 [EA3-133] feature: 스터디 관리 기능 구현 및 조회 스웨거 작성
  src/main/java/grep/neogul_coder/domain/recruitment/RecruitmentErrorCode.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/service/RecruitmentPostSaveService.java
  src/main/java/grep/neogul_coder/domain/study/Study.java
  src/main/java/grep/neogul_coder/domain/study/StudyMember.java
  src/main/java/grep/neogul_coder/domain/study/controller/StudyManagementController.java
  src/main/java/grep/neogul_coder/domain/study/controller/StudyManagementSpecification.java
  src/main/java/grep/neogul_coder/domain/study/controller/dto/response/ExtendParticipationResponse.java
  src/main/java/grep/neogul_coder/domain/study/controller/dto/response/StudyExtensionResponse.java
  src/main/java/grep/neogul_coder/domain/study/exception/code/StudyErrorCode.java
  src/main/java/grep/neogul_coder/domain/study/repository/StudyMemberRepository.java
  src/main/java/grep/neogul_coder/domain/study/service/StudyManagementService.java
  src/main/java/grep/neogul_coder/domain/study/service/StudyService.java
  src/main/resources/data.sql
  src/test/java/grep/neogul_coder/domain/study/service/StudyServiceTest.java
Labels: ✨ feature

#136 [EA3-133] fix: 에러코드 오류 수정
  src/main/java/grep/neogul_coder/domain/study/service/StudyService.java
Labels: 🐛 fix

#142 [EA3-133] feature: 스터디 관리 조회 기능 추가
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/response/RecruitmentPostDetailsInfo.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/response/save/JoinedStudyLoadInfo.java
  src/main/java/grep/neogul_coder/domain/study/Study.java
  src/main/java/grep/neogul_coder/domain/study/controller/StudyManagementController.java
  src/main/java/grep/neogul_coder/domain/study/controller/StudyManagementSpecification.java
  src/main/java/grep/neogul_coder/domain/study/controller/dto/request/ExtendStudyRequest.java
  src/main/java/grep/neogul_coder/domain/study/controller/dto/request/StudyCreateRequest.java
  src/main/java/grep/neogul_coder/domain/study/controller/dto/request/StudyUpdateRequest.java
  src/main/java/grep/neogul_coder/domain/study/controller/dto/response/ExtendParticipationResponse.java
  src/main/java/grep/neogul_coder/domain/study/controller/dto/response/StudyExtensionResponse.java
  src/main/java/grep/neogul_coder/domain/study/controller/dto/response/StudyInfoResponse.java
  src/main/java/grep/neogul_coder/domain/study/controller/dto/response/StudyItemResponse.java
  src/main/java/grep/neogul_coder/domain/study/repository/StudyMemberQueryRepository.java
  src/main/java/grep/neogul_coder/domain/study/repository/StudyQueryRepository.java
  src/main/java/grep/neogul_coder/domain/study/service/StudyManagementService.java
Labels: ✨ feature

#137 [EA3-138] Feature: 모집글 조회 반환값 추가 및 정리
  src/main/java/grep/neogul_coder/domain/main/controller/MainController.java
  src/main/java/grep/neogul_coder/domain/recruitment/comment/controller/dto/response/CommentsWithWriterInfo.java
  src/main/java/grep/neogul_coder/domain/recruitment/comment/repository/RecruitmentPostCommentQueryRepository.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/RecruitmentPostController.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/RecruitmentPostSpecification.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/response/RecruitmentPostCommentPagingInfo.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/response/RecruitmentPostInfo.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/response/RecruitmentPostPagingInfo.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/response/RecruitmentPostWithStudyInfo.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/repository/RecruitmentPostQueryRepository.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/service/RecruitmentPostService.java
  src/main/java/grep/neogul_coder/domain/review/controller/ReviewController.java
  src/main/java/grep/neogul_coder/domain/review/controller/dto/response/JoinedStudiesInfo.java
  src/main/java/grep/neogul_coder/domain/review/service/ReviewService.java
  src/main/java/grep/neogul_coder/global/init/ReviewTagInitializer.java
  src/test/java/grep/neogul_coder/domain/recruitment/post/repository/RecruitmentPostQueryRepositoryTest.java
  src/test/java/grep/neogul_coder/domain/recruitment/post/service/RecruitmentPostServiceTest.java
  src/test/java/grep/neogul_coder/domain/review/controller/service/ReviewServiceTest.java
Labels: ✨ feature

#144 chore: develop → main 브랜치 머지
  src/main/java/grep/neogul_coder/domain/admin/controller/AdminController.java
  src/main/java/grep/neogul_coder/domain/admin/controller/AdminSpecification.java
  src/main/java/grep/neogul_coder/domain/admin/controller/dto/response/AdminRecruitmentPostResponse.java
  src/main/java/grep/neogul_coder/domain/admin/controller/dto/response/AdminStudyResponse.java
  src/main/java/grep/neogul_coder/domain/admin/controller/dto/response/AdminUserResponse.java
  src/main/java/grep/neogul_coder/domain/admin/service/AdminService.java
  src/main/java/grep/neogul_coder/domain/calender/repository/PersonalCalendarQueryRepository.java
  src/main/java/grep/neogul_coder/domain/calender/repository/TeamCalendarQueryRepository.java
  src/main/java/grep/neogul_coder/domain/main/controller/MainController.java
  src/main/java/grep/neogul_coder/domain/prtemplate/service/PrTemplateService.java
  src/main/java/grep/neogul_coder/domain/quiz/controller/AiQuizController.java
  src/main/java/grep/neogul_coder/domain/recruitment/comment/controller/dto/response/CommentsWithWriterInfo.java
  src/main/java/grep/neogul_coder/domain/recruitment/comment/repository/RecruitmentPostCommentQueryRepository.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/RecruitmentPost.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/RecruitmentPostController.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/RecruitmentPostSpecification.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/request/save/RecruitmentPostCreateRequest.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/response/RecruitmentPostCommentPagingInfo.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/response/RecruitmentPostInfo.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/response/RecruitmentPostPagingInfo.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/response/RecruitmentPostWithStudyInfo.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/response/save/JoinedStudyLoadInfo.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/repository/RecruitmentPostQueryRepository.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/repository/RecruitmentPostRepository.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/service/RecruitmentPostService.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/service/request/RecruitmentPostCreateServiceRequest.java
  src/main/java/grep/neogul_coder/domain/review/controller/ReviewController.java
  src/main/java/grep/neogul_coder/domain/review/controller/dto/response/JoinedStudiesInfo.java
  src/main/java/grep/neogul_coder/domain/review/service/ReviewService.java
  src/main/java/grep/neogul_coder/domain/study/Study.java
  src/main/java/grep/neogul_coder/domain/study/controller/StudyManagementController.java
  src/main/java/grep/neogul_coder/domain/study/controller/StudyManagementSpecification.java
  src/main/java/grep/neogul_coder/domain/study/controller/dto/request/ExtendStudyRequest.java
  src/main/java/grep/neogul_coder/domain/study/controller/dto/request/StudyCreateRequest.java
  src/main/java/grep/neogul_coder/domain/study/controller/dto/request/StudyUpdateRequest.java
  src/main/java/grep/neogul_coder/domain/study/controller/dto/response/ExtendParticipationResponse.java
  src/main/java/grep/neogul_coder/domain/study/controller/dto/response/StudyExtensionResponse.java
  src/main/java/grep/neogul_coder/domain/study/controller/dto/response/StudyInfoResponse.java
  src/main/java/grep/neogul_coder/domain/study/controller/dto/response/StudyItemResponse.java
  src/main/java/grep/neogul_coder/domain/study/repository/StudyMemberQueryRepository.java
  src/main/java/grep/neogul_coder/domain/study/repository/StudyQueryRepository.java
  src/main/java/grep/neogul_coder/domain/study/repository/StudyRepository.java
  src/main/java/grep/neogul_coder/domain/study/service/StudyManagementService.java
  src/main/java/grep/neogul_coder/domain/study/service/StudyService.java
  src/main/java/grep/neogul_coder/domain/studyapplication/StudyApplication.java
  src/main/java/grep/neogul_coder/domain/users/controller/UserController.java
  src/main/java/grep/neogul_coder/domain/users/controller/UserSpecification.java
  src/main/java/grep/neogul_coder/domain/users/repository/UserRepository.java
  src/main/java/grep/neogul_coder/domain/users/service/UserService.java
  src/main/java/grep/neogul_coder/global/config/security/SecurityConfig.java
  src/main/java/grep/neogul_coder/global/init/AdminAccountInitializer.java
  src/main/java/grep/neogul_coder/global/init/ReviewTagInitializer.java
  src/main/resources/data.sql
  src/test/java/grep/neogul_coder/domain/recruitment/post/repository/RecruitmentPostQueryRepositoryTest.java
  src/test/java/grep/neogul_coder/domain/recruitment/post/service/RecruitmentPostServiceTest.java
  src/test/java/grep/neogul_coder/domain/review/controller/service/ReviewServiceTest.java
Labels: 🔧 chore

#149 [EA3-138] feature: 모집글 페이징 조회 동적쿼리로 변경
  src/main/java/grep/neogul_coder/domain/main/controller/MainController.java
  src/main/java/grep/neogul_coder/domain/main/controller/MainSpecification.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/RecruitmentPostController.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/RecruitmentPostSpecification.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/request/PagingCondition.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/response/RecruitmentPostPagingInfo.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/repository/RecruitmentPostQueryRepository.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/service/RecruitmentPostService.java
  src/main/java/grep/neogul_coder/domain/study/enums/Category.java
  src/test/java/grep/neogul_coder/domain/recruitment/post/service/RecruitmentPostServiceTest.java
  src/test/java/grep/neogul_coder/domain/study/service/StudyServiceTest.java
Labels: ✨ feature

#150 [EA3-133] feature: 스터디 연장, 연장 참여 기능 구현
  src/main/java/grep/neogul_coder/domain/admin/controller/dto/response/AdminStudyResponse.java
  src/main/java/grep/neogul_coder/domain/study/Study.java
  src/main/java/grep/neogul_coder/domain/study/StudyMember.java
  src/main/java/grep/neogul_coder/domain/study/controller/StudyManagementController.java
  src/main/java/grep/neogul_coder/domain/study/controller/StudyManagementSpecification.java
  src/main/java/grep/neogul_coder/domain/study/controller/dto/request/ExtendStudyRequest.java
  src/main/java/grep/neogul_coder/domain/study/controller/dto/response/ExtendParticipationResponse.java
  src/main/java/grep/neogul_coder/domain/study/controller/dto/response/StudyExtensionResponse.java
  src/main/java/grep/neogul_coder/domain/study/controller/dto/response/StudyImageResponse.java
  src/main/java/grep/neogul_coder/domain/study/controller/dto/response/StudyItemPagingResponse.java
  src/main/java/grep/neogul_coder/domain/study/controller/dto/response/StudyItemResponse.java
  src/main/java/grep/neogul_coder/domain/study/exception/code/StudyErrorCode.java
  src/main/java/grep/neogul_coder/domain/study/repository/StudyMemberQueryRepository.java
  src/main/java/grep/neogul_coder/domain/study/repository/StudyQueryRepository.java
  src/main/java/grep/neogul_coder/domain/study/repository/StudyRepository.java
  src/main/java/grep/neogul_coder/domain/study/service/StudyManagementService.java
  src/main/java/grep/neogul_coder/domain/study/service/StudyService.java
  src/main/resources/data.sql
Labels: ✨ feature

#154 chore: develop → main 브랜치 머지
  src/main/java/grep/neogul_coder/domain/admin/controller/dto/response/AdminStudyResponse.java
  src/main/java/grep/neogul_coder/domain/main/controller/MainController.java
  src/main/java/grep/neogul_coder/domain/main/controller/MainSpecification.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/RecruitmentPostController.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/RecruitmentPostSpecification.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/request/PagingCondition.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/response/RecruitmentPostPagingInfo.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/repository/RecruitmentPostQueryRepository.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/service/RecruitmentPostService.java
  src/main/java/grep/neogul_coder/domain/study/Study.java
  src/main/java/grep/neogul_coder/domain/study/StudyMember.java
  src/main/java/grep/neogul_coder/domain/study/controller/StudyManagementController.java
  src/main/java/grep/neogul_coder/domain/study/controller/StudyManagementSpecification.java
  src/main/java/grep/neogul_coder/domain/study/controller/dto/request/ExtendStudyRequest.java
  src/main/java/grep/neogul_coder/domain/study/controller/dto/response/ExtendParticipationResponse.java
  src/main/java/grep/neogul_coder/domain/study/controller/dto/response/StudyExtensionResponse.java
  src/main/java/grep/neogul_coder/domain/study/controller/dto/response/StudyImageResponse.java
  src/main/java/grep/neogul_coder/domain/study/controller/dto/response/StudyItemPagingResponse.java
  src/main/java/grep/neogul_coder/domain/study/controller/dto/response/StudyItemResponse.java
  src/main/java/grep/neogul_coder/domain/study/enums/Category.java
  src/main/java/grep/neogul_coder/domain/study/exception/code/StudyErrorCode.java
  src/main/java/grep/neogul_coder/domain/study/repository/StudyMemberQueryRepository.java
  src/main/java/grep/neogul_coder/domain/study/repository/StudyQueryRepository.java
  src/main/java/grep/neogul_coder/domain/study/repository/StudyRepository.java
  src/main/java/grep/neogul_coder/domain/study/service/StudyManagementService.java
  src/main/java/grep/neogul_coder/domain/study/service/StudyService.java
  src/main/java/grep/neogul_coder/domain/users/controller/UserController.java
  src/main/java/grep/neogul_coder/domain/users/entity/User.java
  src/main/java/grep/neogul_coder/domain/users/service/UserService.java
  src/main/resources/data.sql
  src/test/java/grep/neogul_coder/domain/recruitment/post/service/RecruitmentPostServiceTest.java
  src/test/java/grep/neogul_coder/domain/study/service/StudyServiceTest.java
Labels: 🔧 chore

#147 [EA3-113] feature : 버디에너지 조회 기능 구현
  src/main/java/grep/neogul_coder/domain/buddy/controller/BuddyEnergyController.java
  src/main/java/grep/neogul_coder/domain/buddy/controller/dto/response/BuddyEnergyResponse.java
  src/main/java/grep/neogul_coder/domain/buddy/entity/BuddyEnergy.java
  src/main/java/grep/neogul_coder/domain/buddy/entity/BuddyLog.java
  src/main/java/grep/neogul_coder/domain/buddy/exception/BuddyEnergyNotFoundException.java
  src/main/java/grep/neogul_coder/domain/buddy/exception/code/BuddyEnergyErrorCode.java
  src/main/java/grep/neogul_coder/domain/buddy/repository/BuddyEnergyLogRepository.java
  src/main/java/grep/neogul_coder/domain/buddy/service/BuddyEnergyService.java
  src/main/java/grep/neogul_coder/domain/review/service/ReviewService.java
  src/main/java/grep/neogul_coder/domain/study/service/StudyService.java
  src/main/java/grep/neogul_coder/domain/users/service/UserService.java
Labels: ✨ feature, ♻️ refactor

#148 [EA3-112] fix: 날짜별 조회 날짜 계산 로직 수정 및 일정 등록 시 Id 값 반환
  src/main/java/grep/neogul_coder/domain/calender/controller/PersonalCalendarController.java
  src/main/java/grep/neogul_coder/domain/calender/controller/PersonalCalendarSpecification.java
  src/main/java/grep/neogul_coder/domain/calender/controller/TeamCalendarController.java
  src/main/java/grep/neogul_coder/domain/calender/controller/TeamCalendarSpecification.java
  src/main/java/grep/neogul_coder/domain/calender/repository/PersonalCalendarQueryRepository.java
  src/main/java/grep/neogul_coder/domain/calender/repository/TeamCalendarQueryRepository.java
  src/main/java/grep/neogul_coder/domain/calender/service/PersonalCalendarService.java
  src/main/java/grep/neogul_coder/domain/calender/service/TeamCalendarService.java
Labels: 🐛 fix

#156 chore: develop → main 브랜치 머지
  src/main/java/grep/neogul_coder/domain/buddy/controller/BuddyEnergyController.java
  src/main/java/grep/neogul_coder/domain/buddy/controller/dto/response/BuddyEnergyResponse.java
  src/main/java/grep/neogul_coder/domain/buddy/entity/BuddyEnergy.java
  src/main/java/grep/neogul_coder/domain/buddy/entity/BuddyLog.java
  src/main/java/grep/neogul_coder/domain/buddy/exception/BuddyEnergyNotFoundException.java
  src/main/java/grep/neogul_coder/domain/buddy/exception/code/BuddyEnergyErrorCode.java
  src/main/java/grep/neogul_coder/domain/buddy/repository/BuddyEnergyLogRepository.java
  src/main/java/grep/neogul_coder/domain/buddy/service/BuddyEnergyService.java
  src/main/java/grep/neogul_coder/domain/calender/controller/PersonalCalendarController.java
  src/main/java/grep/neogul_coder/domain/calender/controller/PersonalCalendarSpecification.java
  src/main/java/grep/neogul_coder/domain/calender/controller/TeamCalendarController.java
  src/main/java/grep/neogul_coder/domain/calender/controller/TeamCalendarSpecification.java
  src/main/java/grep/neogul_coder/domain/calender/repository/PersonalCalendarQueryRepository.java
  src/main/java/grep/neogul_coder/domain/calender/repository/TeamCalendarQueryRepository.java
  src/main/java/grep/neogul_coder/domain/calender/service/PersonalCalendarService.java
  src/main/java/grep/neogul_coder/domain/calender/service/TeamCalendarService.java
  src/main/java/grep/neogul_coder/domain/review/service/ReviewService.java
  src/main/java/grep/neogul_coder/domain/study/service/StudyService.java
  src/main/java/grep/neogul_coder/domain/users/service/UserService.java
Labels: 🔧 chore

#157 [EA3-162] feature: 출석 기능 및 테스트
  src/main/java/grep/neogul_coder/domain/attendance/Attendance.java
  src/main/java/grep/neogul_coder/domain/attendance/controller/AttendanceController.java
  src/main/java/grep/neogul_coder/domain/attendance/controller/AttendanceSpecification.java
  src/main/java/grep/neogul_coder/domain/attendance/controller/dto/response/AttendanceInfoResponse.java
  src/main/java/grep/neogul_coder/domain/attendance/controller/dto/response/AttendanceResponse.java
  src/main/java/grep/neogul_coder/domain/attendance/exception/code/AttendanceErrorCode.java
  src/main/java/grep/neogul_coder/domain/attendance/repository/AttendanceRepository.java
  src/main/java/grep/neogul_coder/domain/attendance/service/AttendanceService.java
  src/main/java/grep/neogul_coder/domain/study/repository/StudyMemberRepository.java
  src/test/java/grep/neogul_coder/domain/attendance/service/AttendanceServiceTest.java
Labels: ✨ feature, 🚨 test

#159 [EA3-163] Feature: 스터디 게시글 CRUD 추가
  src/main/java/grep/neogul_coder/domain/comment/Comment.java
  src/main/java/grep/neogul_coder/domain/quiz/controller/AiQuizController.java
  src/main/java/grep/neogul_coder/domain/study/StudyMember.java
  src/main/java/grep/neogul_coder/domain/study/controller/dto/response/StudyMyContentResponse.java
  src/main/java/grep/neogul_coder/domain/study/controller/dto/response/StudyResponse.java
  src/main/java/grep/neogul_coder/domain/studypost/Category.java
  src/main/java/grep/neogul_coder/domain/studypost/StudyPost.java
  src/main/java/grep/neogul_coder/domain/studypost/StudyPostErrorCode.java
  src/main/java/grep/neogul_coder/domain/studypost/comment/StudyPostComment.java
  src/main/java/grep/neogul_coder/domain/studypost/comment/controller/CommentController.java
  src/main/java/grep/neogul_coder/domain/studypost/comment/controller/CommentSpecification.java
  src/main/java/grep/neogul_coder/domain/studypost/comment/dto/CommentRequest.java
  src/main/java/grep/neogul_coder/domain/studypost/comment/dto/CommentResponse.java
  src/main/java/grep/neogul_coder/domain/studypost/comment/repository/StudyCommentRepository.java
  src/main/java/grep/neogul_coder/domain/studypost/comment/repository/StudyPostCommentQueryRepository.java
  src/main/java/grep/neogul_coder/domain/studypost/controller/StudyPostController.java
  src/main/java/grep/neogul_coder/domain/studypost/controller/StudyPostSpecification.java
  src/main/java/grep/neogul_coder/domain/studypost/controller/dto/StudyPostListResponse.java
  src/main/java/grep/neogul_coder/domain/studypost/controller/dto/request/StudyPostPagingCondition.java
  src/main/java/grep/neogul_coder/domain/studypost/controller/dto/request/StudyPostSaveRequest.java
  src/main/java/grep/neogul_coder/domain/studypost/controller/dto/request/StudyPostUpdateRequest.java
  src/main/java/grep/neogul_coder/domain/studypost/controller/dto/response/CommentInfo.java
  src/main/java/grep/neogul_coder/domain/studypost/controller/dto/response/NoticePostInfo.java
  src/main/java/grep/neogul_coder/domain/studypost/controller/dto/response/PostInfo.java
  src/main/java/grep/neogul_coder/domain/studypost/controller/dto/response/PostPagingInfo.java
  src/main/java/grep/neogul_coder/domain/studypost/controller/dto/response/PostPagingResult.java
  src/main/java/grep/neogul_coder/domain/studypost/controller/dto/response/StudyPostDetailResponse.java
  src/main/java/grep/neogul_coder/domain/studypost/dto/StudyPostDetailResponse.java
  src/main/java/grep/neogul_coder/domain/studypost/dto/StudyPostListResponse.java
  src/main/java/grep/neogul_coder/domain/studypost/dto/StudyPostRequest.java
  src/main/java/grep/neogul_coder/domain/studypost/repository/StudyPostQueryRepository.java
  src/main/java/grep/neogul_coder/domain/studypost/service/StudyPostService.java
  src/main/java/grep/neogul_coder/global/auth/entity/RefreshToken.java
  src/test/java/grep/neogul_coder/domain/recruitment/post/repository/RecruitmentPostStudyPostCommentQueryRepositoryTest.java
  src/test/java/grep/neogul_coder/domain/studypost/repository/StudyPostQueryRepositoryTest.java
  src/test/java/grep/neogul_coder/domain/studypost/service/StudyPostServiceTest.java
Labels: ✨ feature

#161 [EA3-138] feature: 모집글 수정시 모집 마감 기간 추가
  src/main/java/grep/neogul_coder/domain/recruitment/RecruitmentErrorCode.java
  src/main/java/grep/neogul_coder/domain/recruitment/comment/RecruitmentPostComment.java
  src/main/java/grep/neogul_coder/domain/recruitment/comment/controller/RecruitmentPostCommentController.java
  src/main/java/grep/neogul_coder/domain/recruitment/comment/controller/RecruitmentPostCommentSpecification.java
  src/main/java/grep/neogul_coder/domain/recruitment/comment/controller/dto/request/RecruitmentCommentSaveRequest.java
  src/main/java/grep/neogul_coder/domain/recruitment/comment/controller/dto/request/RecruitmentCommentUpdateRequest.java
  src/main/java/grep/neogul_coder/domain/recruitment/comment/repository/RecruitmentPostCommentQueryRepository.java
  src/main/java/grep/neogul_coder/domain/recruitment/comment/service/RecruitmentPostCommentService.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/RecruitmentPost.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/controller/dto/request/RecruitmentPostUpdateRequest.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/repository/RecruitmentPostQueryRepository.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/service/RecruitmentPostService.java
  src/main/java/grep/neogul_coder/domain/recruitment/post/service/request/RecruitmentPostUpdateServiceRequest.java
Labels: ✨ feature

#162 [EA3-111] feature : 그룹채팅 과거 채팅 페이징 조회 API 구현 및 Swagger 문서 수정
  build.gradle
  src/main/java/grep/neogul_coder/domain/groupchat/controller/GroupChatRestController.java
  src/main/java/grep/neogul_coder/domain/groupchat/controller/GroupChatRestSpecification.java
  src/main/java/grep/neogul_coder/domain/groupchat/controller/GroupChatSwaggerSpecification.java
  src/main/java/grep/neogul_coder/domain/groupchat/controller/GroupChatWebSocketController.java
  src/main/java/grep/neogul_coder/domain/groupchat/controller/dto/requset/GroupChatMessageRequestDto.java
  src/main/java/grep/neogul_coder/domain/groupchat/controller/dto/response/GroupChatMessageResponseDto.java
  src/main/java/grep/neogul_coder/domain/groupchat/controller/dto/response/GroupChatSwaggerResponse.java
  src/main/java/grep/neogul_coder/domain/groupchat/entity/GroupChatMessage.java
  src/main/java/grep/neogul_coder/domain/groupchat/repository/GroupChatMessageRepository.java
  src/main/java/grep/neogul_coder/domain/groupchat/repository/GroupChatRoomRepository.java
  src/main/java/grep/neogul_coder/domain/groupchat/service/GroupChatService.java
  src/main/java/grep/neogul_coder/domain/study/repository/StudyMemberRepository.java
  src/main/java/grep/neogul_coder/global/config/WebSocketConfig.java
  src/main/resources/data.sql
Labels: 📝 docs, ✨ feature

#168 [EA3-112] refactor : 개인/팀 캘린더 일정 등록 API 개선
  src/main/java/grep/neogul_coder/domain/calender/controller/PersonalCalendarController.java
  src/main/java/grep/neogul_coder/domain/calender/controller/PersonalCalendarSpecification.java
  src/main/java/grep/neogul_coder/domain/calender/controller/TeamCalendarController.java
  src/main/java/grep/neogul_coder/domain/calender/controller/TeamCalendarSpecification.java
  src/main/java/grep/neogul_coder/domain/calender/service/PersonalCalendarService.java
  src/main/java/grep/neogul_coder/domain/calender/service/TeamCalendarService.java
Labels: ♻️ refactor

#169 [EA3-134] refactor: 스터디 모임시간 조율 전체 구조 리팩터링 및 응답/요청 구조 개선
  src/main/java/grep/neogul_coder/domain/timevote/controller/TimeVoteController.java
  src/main/java/grep/neogul_coder/domain/timevote/controller/TimeVoteSpecification.java
  src/main/java/grep/neogul_coder/domain/timevote/dto/request/TimeVoteBulkCreateRequest.java
  src/main/java/grep/neogul_coder/domain/timevote/dto/request/TimeVoteBulkDeleteRequest.java
  src/main/java/grep/neogul_coder/domain/timevote/dto/request/TimeVoteBulkUpdateRequest.java
  src/main/java/grep/neogul_coder/domain/timevote/dto/request/TimeVoteCreateRequest.java
  src/main/java/grep/neogul_coder/domain/timevote/dto/request/TimeVoteDeleteRequest.java
  src/main/java/grep/neogul_coder/domain/timevote/dto/request/TimeVotePeriodCreateRequest.java
  src/main/java/grep/neogul_coder/domain/timevote/dto/request/TimeVoteUpdateRequest.java
  src/main/java/grep/neogul_coder/domain/timevote/dto/response/TimeVotePeriodResponse.java
  src/main/java/grep/neogul_coder/domain/timevote/dto/response/TimeVoteResponse.java
  src/main/java/grep/neogul_coder/domain/timevote/dto/response/TimeVoteStatListResponse.java
  src/main/java/grep/neogul_coder/domain/timevote/dto/response/TimeVoteStatResponse.java
  src/main/java/grep/neogul_coder/domain/timevote/dto/response/TimeVoteSubmissionStatusResponse.java
  src/main/java/grep/neogul_coder/domain/timevote/entity/TimeVote.java
  src/main/java/grep/neogul_coder/domain/timevote/entity/TimeVotePeriod.java
  src/main/java/grep/neogul_coder/domain/timevote/entity/TimeVoteStat.java
  src/main/resources/data.sql
Labels: ✨ feature, ♻️ refactor

#170 chore: develop → main 브랜치 머지
  src/main/java/grep/neogul_coder/domain/calender/controller/PersonalCalendarController.java
  src/main/java/grep/neogul_coder/domain/calender/controller/PersonalCalendarSpecification.java
  src/main/java/grep/neogul_coder/domain/calender/controller/TeamCalendarController.java
  src/main/java/grep/neogul_coder/domain/calender/controller/TeamCalendarSpecification.java
  src/main/java/grep/neogul_coder/domain/calender/service/PersonalCalendarService.java
  src/main/java/grep/neogul_coder/domain/calender/service/TeamCalendarService.java
  src/main/java/grep/neogul_coder/domain/studypost/controller/StudyPostController.java
  src/main/java/grep/neogul_coder/domain/studypost/controller/StudyPostSpecification.java
  src/main/java/grep/neogul_coder/domain/studypost/controller/dto/request/StudyPostSaveRequest.java
  src/main/java/grep/neogul_coder/domain/studypost/repository/StudyPostQueryRepository.java
  src/main/java/grep/neogul_coder/domain/studypost/service/StudyPostService.java
  src/main/java/grep/neogul_coder/domain/timevote/controller/TimeVoteController.java
  src/main/java/grep/neogul_coder/domain/timevote/controller/TimeVoteSpecification.java
  src/main/java/grep/neogul_coder/domain/timevote/dto/request/TimeVoteBulkCreateRequest.java
  src/main/java/grep/neogul_coder/domain/timevote/dto/request/TimeVoteBulkDeleteRequest.java
  src/main/java/grep/neogul_coder/domain/timevote/dto/request/TimeVoteBulkUpdateRequest.java
  src/main/java/grep/neogul_coder/domain/timevote/dto/request/TimeVoteCreateRequest.java
  src/main/java/grep/neogul_coder/domain/timevote/dto/request/TimeVoteDeleteRequest.java
  src/main/java/grep/neogul_coder/domain/timevote/dto/request/TimeVotePeriodCreateRequest.java
  src/main/java/grep/neogul_coder/domain/timevote/dto/request/TimeVoteUpdateRequest.java
  src/main/java/grep/neogul_coder/domain/timevote/dto/response/TimeVotePeriodResponse.java
  src/main/java/grep/neogul_coder/domain/timevote/dto/response/TimeVoteResponse.java
  src/main/java/grep/neogul_coder/domain/timevote/dto/response/TimeVoteStatListResponse.java
  src/main/java/grep/neogul_coder/domain/timevote/dto/response/TimeVoteStatResponse.java
  src/main/java/grep/neogul_coder/domain/timevote/dto/response/TimeVoteSubmissionStatusResponse.java
  src/main/java/grep/neogul_coder/domain/timevote/entity/TimeVote.java
  src/main/java/grep/neogul_coder/domain/timevote/entity/TimeVotePeriod.java
  src/main/java/grep/neogul_coder/domain/timevote/entity/TimeVoteStat.java
  src/main/java/grep/neogul_coder/global/utils/upload/uploader/GcpFileUploader.java
  src/main/java/grep/neogul_coder/global/utils/upload/uploader/LocalFileUploader.java
  src/main/resources/data.sql
Labels: 🔧 chore

#171 [EA3-134] chore: 스터디 모임시간 조율 - service 제외
  src/main/java/grep/neogul_coder/domain/timevote/controller/TimeVoteController.java
Labels: 🔧 chore

#175 [EA3-173] 회원가입 시 메일을 통한 인증 기능 추가
  build.gradle
  src/main/java/grep/neogul_coder/domain/users/controller/UserController.java
  src/main/java/grep/neogul_coder/domain/users/controller/UserSpecification.java
  src/main/java/grep/neogul_coder/domain/users/controller/dto/response/UserResponse.java
  src/main/java/grep/neogul_coder/domain/users/entity/User.java
  src/main/java/grep/neogul_coder/domain/users/exception/NotVerifiedEmailException.java
  src/main/java/grep/neogul_coder/domain/users/exception/UnActivatedUserException.java
  src/main/java/grep/neogul_coder/domain/users/exception/advice/UserAdvice.java
  src/main/java/grep/neogul_coder/domain/users/exception/code/UserErrorCode.java
  src/main/java/grep/neogul_coder/domain/users/service/EmailVerificationService.java
  src/main/java/grep/neogul_coder/domain/users/service/UserService.java
  src/main/java/grep/neogul_coder/global/auth/service/AuthService.java
  src/main/java/grep/neogul_coder/global/config/MailConfig.java
  src/main/java/grep/neogul_coder/global/config/security/SecurityConfig.java
  src/main/java/grep/neogul_coder/global/response/ApiResponse.java
Labels: ✨ feature

#174 [EA3-111] feature : dto/서비스 리팩토링 및 그룹 채팅 테스트를 위한 임시 html 파일 생성
  src/main/java/grep/neogul_coder/domain/groupchat/controller/dto/requset/GroupChatMessageRequestDto.java
  src/main/java/grep/neogul_coder/domain/groupchat/controller/dto/requset/GroupChatSwaggerRequest.java
  src/main/java/grep/neogul_coder/domain/groupchat/controller/dto/response/GroupChatMessageResponseDto.java
  src/main/java/grep/neogul_coder/domain/groupchat/entity/GroupChatMessage.java
  src/main/java/grep/neogul_coder/domain/groupchat/repository/GroupChatMessageRepository.java
  src/main/java/grep/neogul_coder/domain/groupchat/service/GroupChatService.java
  src/main/resources/data.sql
  src/main/resources/static/Chat-Test.html
Labels: ✨ feature, ♻️ refactor

#181 [EA3-113] feature : 버디에너지 스터디 + 1/ 리더 + 2 점 구현
  src/main/java/grep/neogul_coder/NeogulCoderApplication.java
  src/main/java/grep/neogul_coder/domain/buddy/service/BuddyEnergyService.java
  src/main/java/grep/neogul_coder/domain/study/service/StudySchedulerService.java
Labels: ✨ feature

#178 [EA3-112] feature : 팀 캘린더 월 단위 일정 조회 API 추가
  src/main/java/grep/neogul_coder/domain/calender/controller/TeamCalendarController.java
  src/main/java/grep/neogul_coder/domain/calender/controller/TeamCalendarSpecification.java
  src/main/java/grep/neogul_coder/domain/calender/repository/TeamCalendarQueryRepository.java
  src/main/java/grep/neogul_coder/domain/calender/service/TeamCalendarService.java
Labels: ✨ feature

#185 [EA3-134] refactor : 스터디 모임 일정 조율 - 스터디원/팀장 여부 및 투표 시간 검증 로직 개선
  src/main/java/grep/neogul_coder/domain/timevote/controller/TimeVoteController.java
  src/main/java/grep/neogul_coder/domain/timevote/dto/request/TimeVoteCreateRequest.java
  src/main/java/grep/neogul_coder/domain/timevote/exception/code/TimeVoteErrorCode.java
  src/main/java/grep/neogul_coder/domain/timevote/repository/TimeVoteRepository.java
  src/main/java/grep/neogul_coder/domain/timevote/service/TimeVotePeriodService.java
  src/main/java/grep/neogul_coder/domain/timevote/service/TimeVoteService.java
Labels: ♻️ refactor, 🔧 chore

#188 [EA3-161] refactor: 스터디 생성, 수정 이미지 업로드 환경 분기 처리 수정
  src/main/java/grep/neogul_coder/domain/study/service/StudyService.java
Labels: ♻️ refactor

#189 [EA3-167] feature: 스터디 목록 조회 및 필터링 추가
  src/main/java/grep/neogul_coder/domain/main/controller/MainController.java
  src/main/java/grep/neogul_coder/domain/main/controller/MainSpecification.java
  src/main/java/grep/neogul_coder/domain/main/controller/dto/response/MainResponse.java
  src/main/java/grep/neogul_coder/domain/study/controller/StudyController.java
  src/main/java/grep/neogul_coder/domain/study/controller/StudySpecification.java
  src/main/java/grep/neogul_coder/domain/study/controller/dto/response/StudyItemPagingResponse.java
  src/main/java/grep/neogul_coder/domain/study/repository/StudyQueryRepository.java
  src/main/java/grep/neogul_coder/domain/study/service/StudyService.java
  src/test/java/grep/neogul_coder/domain/study/service/StudyServiceTest.java
Labels: ✨ feature

#190 [EA3-168] feature: 스터디 신청 목록 페이지네이션 및 필터링
  src/main/java/grep/neogul_coder/domain/studyapplication/controller/ApplicationController.java
  src/main/java/grep/neogul_coder/domain/studyapplication/controller/ApplicationSpecification.java
  src/main/java/grep/neogul_coder/domain/studyapplication/controller/dto/response/MyApplicationPagingResponse.java
  src/main/java/grep/neogul_coder/domain/studyapplication/repository/ApplicationQueryRepository.java
  src/main/java/grep/neogul_coder/domain/studyapplication/service/ApplicationService.java
Labels: ✨ feature

#193 Fix:PR 템플릿으로 인해 회원 생성 안되는 문제와 data.sql 회원 비밀번호 수정
  src/main/java/grep/neogulcoder/domain/prtemplate/entity/PrTemplate.java
  src/main/resources/data.sql
Labels: 🐛 fix

#194 chore: develop → main 브랜치 머지
  src/main/java/grep/neogulcoder/domain/prtemplate/entity/PrTemplate.java
  src/main/resources/data.sql
Labels: 🔧 chore

#197 chore: develop → main 브랜치 머지
  src/main/java/grep/neogulcoder/domain/study/controller/dto/request/StudyCreateRequest.java
  src/main/java/grep/neogulcoder/global/config/OctetStreamReadMsgConverter.java
  src/main/java/grep/neogulcoder/global/config/WebConfig.java
Labels: 🔧 chore

#198 [EA3-161] refactor: 스터디 생성, 수정 request imageUrl 필드 삭제
  src/main/java/grep/neogulcoder/domain/study/controller/StudyController.java
  src/main/java/grep/neogulcoder/domain/study/controller/dto/request/StudyCreateRequest.java
  src/main/java/grep/neogulcoder/domain/study/controller/dto/request/StudyUpdateRequest.java
Labels: ♻️ refactor

#199 [EA3-167] feature: 스터디 조회 기능 구현
  src/main/java/grep/neogulcoder/domain/study/controller/StudyController.java
  src/main/java/grep/neogulcoder/domain/study/controller/dto/response/StudyResponse.java
  src/main/java/grep/neogulcoder/domain/study/service/StudyService.java
  src/main/java/grep/neogulcoder/domain/studypost/controller/dto/response/FreePostInfo.java
  src/main/java/grep/neogulcoder/domain/studypost/repository/StudyPostQueryRepository.java
  src/main/java/grep/neogulcoder/domain/studypost/repository/StudyPostRepository.java
Labels: ✨ feature

#201 chore: develop → main 브랜치 머지
  src/main/java/grep/neogulcoder/domain/recruitment/post/controller/RecruitmentPostController.java
  src/main/java/grep/neogulcoder/domain/recruitment/post/controller/RecruitmentPostSpecification.java
  src/main/java/grep/neogulcoder/domain/recruitment/post/controller/dto/response/RecruitmentApplicationPagingInfo.java
  src/main/java/grep/neogulcoder/domain/study/controller/StudyController.java
  src/main/java/grep/neogulcoder/domain/study/controller/dto/request/StudyCreateRequest.java
  src/main/java/grep/neogulcoder/domain/study/controller/dto/request/StudyUpdateRequest.java
  src/main/java/grep/neogulcoder/domain/study/controller/dto/response/StudyResponse.java
  src/main/java/grep/neogulcoder/domain/study/service/StudyService.java
  src/main/java/grep/neogulcoder/domain/studyapplication/controller/ApplicationController.java
  src/main/java/grep/neogulcoder/domain/studyapplication/controller/ApplicationSpecification.java
  src/main/java/grep/neogulcoder/domain/studyapplication/controller/dto/response/ReceivedApplicationPagingResponse.java
  src/main/java/grep/neogulcoder/domain/studyapplication/controller/dto/response/ReceivedApplicationResponse.java
  src/main/java/grep/neogulcoder/domain/studyapplication/repository/ApplicationQueryRepository.java
  src/main/java/grep/neogulcoder/domain/studyapplication/repository/ApplicationRepository.java
  src/main/java/grep/neogulcoder/domain/studyapplication/service/ApplicationService.java
  src/main/java/grep/neogulcoder/domain/studypost/controller/dto/response/FreePostInfo.java
  src/main/java/grep/neogulcoder/domain/studypost/repository/StudyPostQueryRepository.java
  src/main/java/grep/neogulcoder/domain/studypost/repository/StudyPostRepository.java
  src/main/java/grep/neogulcoder/domain/timevote/controller/TimeVoteController.java
  src/main/java/grep/neogulcoder/domain/timevote/controller/TimeVoteSpecification.java
  src/main/java/grep/neogulcoder/domain/timevote/dto/response/TimeVoteStatListResponse.java
  src/main/java/grep/neogulcoder/domain/timevote/dto/response/TimeVoteStatResponse.java
  src/main/java/grep/neogulcoder/domain/timevote/entity/TimeVotePeriod.java
  src/main/java/grep/neogulcoder/domain/timevote/entity/TimeVoteStat.java
  src/main/java/grep/neogulcoder/domain/timevote/exception/code/TimeVoteErrorCode.java
  src/main/java/grep/neogulcoder/domain/timevote/repository/TimeVoteStatQueryRepository.java
  src/main/java/grep/neogulcoder/domain/timevote/repository/TimeVoteStatRepository.java
  src/main/java/grep/neogulcoder/domain/timevote/service/TimeVotePeriodService.java
  src/main/java/grep/neogulcoder/domain/timevote/service/TimeVoteService.java
  src/main/java/grep/neogulcoder/domain/timevote/service/TimeVoteStatService.java
  src/main/resources/data.sql
Labels: 🔧 chore

#203 [EA3-138] Fix: 모집글 검색시 필수 조건 제거
  src/main/java/grep/neogulcoder/domain/recruitment/post/controller/RecruitmentPostController.java
Labels: 🐛 fix

#205 [EA3-168] refactor: 모집글 신청 목록 조회 이미지 필드 추가 및 쿼리 수정
  src/main/java/grep/neogulcoder/domain/studyapplication/controller/dto/response/ReceivedApplicationPagingResponse.java
  src/main/java/grep/neogulcoder/domain/studyapplication/controller/dto/response/ReceivedApplicationResponse.java
  src/main/java/grep/neogulcoder/domain/studyapplication/repository/ApplicationQueryRepository.java
Labels: ♻️ refactor

#206 [EA3-111] feature : 스터디 생성 시 채팅방 연동 및 임시화면으로 테스트
  src/main/java/grep/neogulcoder/domain/groupchat/controller/GroupChatWebSocketController.java
  src/main/java/grep/neogulcoder/domain/groupchat/entity/GroupChatRoom.java
  src/main/java/grep/neogulcoder/domain/groupchat/service/GroupChatService.java
  src/main/java/grep/neogulcoder/domain/study/service/StudyService.java
  src/main/java/grep/neogulcoder/global/config/security/SecurityConfig.java
Labels: ✨ feature

#209 chore: develop → main 브랜치 머지
  src/main/java/grep/neogulcoder/domain/groupchat/controller/GroupChatWebSocketController.java
  src/main/java/grep/neogulcoder/domain/groupchat/entity/GroupChatRoom.java
  src/main/java/grep/neogulcoder/domain/groupchat/service/GroupChatService.java
  src/main/java/grep/neogulcoder/domain/recruitment/post/controller/RecruitmentPostController.java
  src/main/java/grep/neogulcoder/domain/recruitment/post/service/RecruitmentPostSaveService.java
  src/main/java/grep/neogulcoder/domain/review/controller/ReviewController.java
  src/main/java/grep/neogulcoder/domain/review/controller/ReviewSpecification.java
  src/main/java/grep/neogulcoder/domain/review/controller/dto/response/ReviewTargetStudiesInfo.java
  src/main/java/grep/neogulcoder/domain/review/repository/ReviewQueryRepository.java
  src/main/java/grep/neogulcoder/domain/review/service/ReviewService.java
  src/main/java/grep/neogulcoder/domain/study/Study.java
  src/main/java/grep/neogulcoder/domain/study/repository/StudyMemberQueryRepository.java
  src/main/java/grep/neogulcoder/domain/study/repository/StudyMemberRepository.java
  src/main/java/grep/neogulcoder/domain/study/service/StudySchedulerService.java
  src/main/java/grep/neogulcoder/domain/study/service/StudyService.java
  src/main/java/grep/neogulcoder/domain/studyapplication/controller/dto/response/ReceivedApplicationPagingResponse.java
  src/main/java/grep/neogulcoder/domain/studyapplication/controller/dto/response/ReceivedApplicationResponse.java
  src/main/java/grep/neogulcoder/domain/studyapplication/repository/ApplicationQueryRepository.java
  src/main/java/grep/neogulcoder/domain/studypost/controller/dto/request/StudyPostSaveRequest.java
  src/main/java/grep/neogulcoder/domain/studypost/service/StudyPostService.java
  src/main/java/grep/neogulcoder/domain/users/entity/User.java
  src/main/java/grep/neogulcoder/global/config/security/SecurityConfig.java
  src/test/java/grep/neogulcoder/domain/recruitment/post/service/RecruitmentPostServiceTest.java
  src/test/java/grep/neogulcoder/domain/review/controller/service/ReviewServiceTest.java
  src/test/java/grep/neogulcoder/domain/study/StudyTest.java
  src/test/java/grep/neogulcoder/domain/study/repository/StudyMemberQueryRepositoryTest.java
  src/test/java/grep/neogulcoder/domain/study/service/StudyServiceTest.java
  src/test/java/grep/neogulcoder/domain/studypost/service/StudyPostServiceTest.java
Labels: 🔧 chore

#210 [EA3-178]Feature: 알람 및 알람 메시지 인프라 구현
  src/main/java/grep/neogulcoder/domain/alram/controller/AlarmController.java
  src/main/java/grep/neogulcoder/domain/alram/controller/AlarmSpecification.java
  src/main/java/grep/neogulcoder/domain/alram/entity/Alarm.java
  src/main/java/grep/neogulcoder/domain/alram/repository/AlarmRepository.java
  src/main/java/grep/neogulcoder/domain/alram/service/AlarmService.java
  src/main/java/grep/neogulcoder/domain/alram/type/AlarmType.java
  src/main/java/grep/neogulcoder/domain/alram/type/DomainType.java
  src/main/java/grep/neogulcoder/domain/study/controller/StudyManagementController.java
  src/main/java/grep/neogulcoder/domain/study/service/StudyManagementService.java
  src/main/java/grep/neogulcoder/domain/users/controller/UserController.java
  src/main/java/grep/neogulcoder/domain/users/controller/UserSpecification.java
  src/main/java/grep/neogulcoder/domain/users/controller/dto/response/AllUserResponse.java
  src/main/java/grep/neogulcoder/domain/users/repository/UserRepository.java
  src/main/java/grep/neogulcoder/domain/users/service/UserService.java
  src/main/java/grep/neogulcoder/global/provider/InviteMessageProvider.java
  src/main/java/grep/neogulcoder/global/provider/MessageProvidable.java
  src/main/java/grep/neogulcoder/global/provider/finder/MessageFinder.java
Labels: ✨ feature

#212 [EA3-156] Feature: 리뷰 대상 스터디 조회 수정
  src/main/java/grep/neogulcoder/domain/buddy/entity/BuddyEnergy.java
  src/main/java/grep/neogulcoder/domain/review/ReviewType.java
  src/main/java/grep/neogulcoder/domain/review/controller/ReviewController.java
  src/main/java/grep/neogulcoder/domain/review/controller/ReviewSpecification.java
  src/main/java/grep/neogulcoder/domain/review/service/ReviewService.java
  src/main/java/grep/neogulcoder/domain/study/Studies.java
  src/main/java/grep/neogulcoder/domain/study/StudyMember.java
  src/main/java/grep/neogulcoder/domain/study/StudyMembers.java
  src/main/java/grep/neogulcoder/domain/study/repository/StudyMemberQueryRepository.java
  src/test/java/grep/neogulcoder/domain/review/controller/service/ReviewServiceTest.java
Labels: ✨ feature

#213 [EA3-134] fix: TimeVoteStat 저장 시 version=null 방지를 위한 flush 및 기본값 설정 + 투표 기간 생성시 마지막날 23:59:59로 자동 보정되게 수정
  src/main/java/grep/neogulcoder/domain/timevote/controller/TimeVoteController.java
  src/main/java/grep/neogulcoder/domain/timevote/dto/request/TimeVotePeriodCreateRequest.java
  src/main/java/grep/neogulcoder/domain/timevote/entity/TimeVoteStat.java
  src/main/java/grep/neogulcoder/domain/timevote/repository/TimeVoteStatQueryRepository.java
  src/main/java/grep/neogulcoder/domain/timevote/service/TimeVotePeriodService.java
  src/main/java/grep/neogulcoder/domain/timevote/service/TimeVoteService.java
  src/main/resources/data.sql
Labels: 🐛 fix, ♻️ refactor

#215 [EA3-168] feature: 스터디 신청, 신청 승인 예외 추가
  src/main/java/grep/neogulcoder/domain/study/repository/StudyMemberQueryRepository.java
  src/main/java/grep/neogulcoder/domain/study/service/StudyService.java
  src/main/java/grep/neogulcoder/domain/studyapplication/exception/code/ApplicationErrorCode.java
  src/main/java/grep/neogulcoder/domain/studyapplication/service/ApplicationService.java
  src/test/java/grep/neogulcoder/domain/studyapplication/service/ApplicationServiceTest.java
Labels: ✨ feature

#214 [EA3-178]Feature:스터디 초대 및 수락/거절 구현
  src/main/java/grep/neogulcoder/domain/alram/controller/AlarmController.java
  src/main/java/grep/neogulcoder/domain/alram/controller/AlarmSpecification.java
  src/main/java/grep/neogulcoder/domain/alram/controller/dto/response/AlarmResponse.java
  src/main/java/grep/neogulcoder/domain/alram/exception/code/AlarmErrorCode.java
  src/main/java/grep/neogulcoder/domain/alram/service/AlarmService.java
  src/main/java/grep/neogulcoder/domain/study/controller/StudyManagementController.java
  src/main/java/grep/neogulcoder/domain/study/event/StudyInviteEvent.java
  src/main/java/grep/neogulcoder/domain/study/service/StudyManagementService.java
  src/main/java/grep/neogulcoder/domain/study/service/StudyService.java
  src/main/java/grep/neogulcoder/domain/users/controller/UserController.java
  src/main/java/grep/neogulcoder/domain/users/exception/code/UserErrorCode.java
  src/main/java/grep/neogulcoder/global/provider/InviteMessageProvider.java
  src/main/java/grep/neogulcoder/global/provider/MessageProvidable.java
  src/main/java/grep/neogulcoder/global/provider/finder/MessageFinder.java
Labels: ✨ feature

#217 chore: develop → main 브랜치 머지
  src/main/java/grep/neogulcoder/domain/alram/controller/AlarmController.java
  src/main/java/grep/neogulcoder/domain/alram/controller/AlarmSpecification.java
  src/main/java/grep/neogulcoder/domain/alram/controller/dto/response/AlarmResponse.java
  src/main/java/grep/neogulcoder/domain/alram/entity/Alarm.java
  src/main/java/grep/neogulcoder/domain/alram/exception/code/AlarmErrorCode.java
  src/main/java/grep/neogulcoder/domain/alram/repository/AlarmRepository.java
  src/main/java/grep/neogulcoder/domain/alram/service/AlarmService.java
  src/main/java/grep/neogulcoder/domain/alram/type/AlarmType.java
  src/main/java/grep/neogulcoder/domain/alram/type/DomainType.java
  src/main/java/grep/neogulcoder/domain/buddy/entity/BuddyEnergy.java
  src/main/java/grep/neogulcoder/domain/groupchat/controller/GroupChatRestController.java
  src/main/java/grep/neogulcoder/domain/groupchat/controller/GroupChatRestSpecification.java
  src/main/java/grep/neogulcoder/domain/groupchat/controller/GroupChatSwaggerController.java
  src/main/java/grep/neogulcoder/domain/groupchat/controller/GroupChatSwaggerSpecification.java
  src/main/java/grep/neogulcoder/domain/groupchat/controller/GroupChatWebSocketController.java
  src/main/java/grep/neogulcoder/domain/groupchat/controller/dto/requset/GroupChatMessageRequestDto.java
  src/main/java/grep/neogulcoder/domain/groupchat/controller/dto/requset/GroupChatSwaggerRequest.java
  src/main/java/grep/neogulcoder/domain/groupchat/controller/dto/response/GroupChatMessageResponseDto.java
  src/main/java/grep/neogulcoder/domain/groupchat/controller/dto/response/GroupChatSwaggerResponse.java
  src/main/java/grep/neogulcoder/domain/groupchat/service/GroupChatService.java
  src/main/java/grep/neogulcoder/domain/review/ReviewType.java
  src/main/java/grep/neogulcoder/domain/review/controller/ReviewController.java
  src/main/java/grep/neogulcoder/domain/review/controller/ReviewSpecification.java
  src/main/java/grep/neogulcoder/domain/review/service/ReviewService.java
  src/main/java/grep/neogulcoder/domain/study/Studies.java
  src/main/java/grep/neogulcoder/domain/study/Study.java
  src/main/java/grep/neogulcoder/domain/study/StudyMember.java
  src/main/java/grep/neogulcoder/domain/study/StudyMembers.java
  src/main/java/grep/neogulcoder/domain/study/controller/StudyManagementController.java
  src/main/java/grep/neogulcoder/domain/study/controller/dto/request/StudyCreateRequest.java
  src/main/java/grep/neogulcoder/domain/study/event/StudyInviteEvent.java
  src/main/java/grep/neogulcoder/domain/study/exception/code/StudyErrorCode.java
  src/main/java/grep/neogulcoder/domain/study/repository/StudyMemberQueryRepository.java
  src/main/java/grep/neogulcoder/domain/study/repository/StudyRepository.java
  src/main/java/grep/neogulcoder/domain/study/service/StudyManagementService.java
  src/main/java/grep/neogulcoder/domain/study/service/StudyService.java
  src/main/java/grep/neogulcoder/domain/studyapplication/exception/code/ApplicationErrorCode.java
  src/main/java/grep/neogulcoder/domain/studyapplication/service/ApplicationService.java
  src/main/java/grep/neogulcoder/domain/studypost/controller/dto/response/FreePostInfo.java
  src/main/java/grep/neogulcoder/domain/studypost/controller/dto/response/NoticePostInfo.java
  src/main/java/grep/neogulcoder/domain/timevote/controller/TimeVoteController.java
  src/main/java/grep/neogulcoder/domain/timevote/dto/request/TimeVotePeriodCreateRequest.java
  src/main/java/grep/neogulcoder/domain/timevote/entity/TimeVoteStat.java
  src/main/java/grep/neogulcoder/domain/timevote/repository/TimeVoteStatQueryRepository.java
  src/main/java/grep/neogulcoder/domain/timevote/service/TimeVotePeriodService.java
  src/main/java/grep/neogulcoder/domain/timevote/service/TimeVoteService.java
  src/main/java/grep/neogulcoder/domain/users/controller/UserController.java
  src/main/java/grep/neogulcoder/domain/users/controller/UserSpecification.java
  src/main/java/grep/neogulcoder/domain/users/controller/dto/response/AllUserResponse.java
  src/main/java/grep/neogulcoder/domain/users/exception/code/UserErrorCode.java
  src/main/java/grep/neogulcoder/domain/users/repository/UserRepository.java
  src/main/java/grep/neogulcoder/domain/users/service/UserService.java
  src/main/java/grep/neogulcoder/global/provider/InviteMessageProvider.java
  src/main/java/grep/neogulcoder/global/provider/MessageProvidable.java
  src/main/java/grep/neogulcoder/global/provider/finder/MessageFinder.java
  src/main/resources/data.sql
  src/main/resources/static/Chat-Test.html
  src/test/java/grep/neogulcoder/domain/review/controller/service/ReviewServiceTest.java
  src/test/java/grep/neogulcoder/domain/study/service/StudyServiceTest.java
  src/test/java/grep/neogulcoder/domain/studyapplication/service/ApplicationServiceTest.java
Labels: 🔧 chore

#218 [EA3-134] feature : 시간 투표 기간 생성 시 팀원에게 알림 전송 기능 추가
  src/main/java/grep/neogulcoder/domain/alram/exception/code/AlarmErrorCode.java
  src/main/java/grep/neogulcoder/domain/alram/type/AlarmType.java
  src/main/java/grep/neogulcoder/domain/alram/type/DomainType.java
  src/main/java/grep/neogulcoder/domain/timevote/dto/response/TimeVotePeriodResponse.java
  src/main/java/grep/neogulcoder/domain/timevote/provider/TimeVoteMessageProvider.java
  src/main/java/grep/neogulcoder/domain/timevote/service/TimeVotePeriodService.java
  src/main/resources/data.sql
Labels: ✨ feature, ♻️ refactor, 🔧 chore

#225 [EA3-68] chore: develop → main 브랜치 머지
  src/main/java/grep/neogulcoder/domain/alram/exception/code/AlarmErrorCode.java
  src/main/java/grep/neogulcoder/domain/alram/service/AlarmService.java
  src/main/java/grep/neogulcoder/domain/alram/type/AlarmType.java
  src/main/java/grep/neogulcoder/domain/alram/type/DomainType.java
  src/main/java/grep/neogulcoder/domain/study/event/StudyExtendEvent.java
  src/main/java/grep/neogulcoder/domain/study/event/StudyExtensionReminderEvent.java
  src/main/java/grep/neogulcoder/domain/study/exception/code/StudyErrorCode.java
  src/main/java/grep/neogulcoder/domain/study/provider/InviteMessageProvider.java
  src/main/java/grep/neogulcoder/domain/study/provider/StudyExtendMessageProvider.java
  src/main/java/grep/neogulcoder/domain/study/provider/StudyExtensionReminderMessageProvider.java
  src/main/java/grep/neogulcoder/domain/study/repository/StudyMemberRepository.java
  src/main/java/grep/neogulcoder/domain/study/scheduler/StudyScheduler.java
  src/main/java/grep/neogulcoder/domain/study/service/StudyManagementService.java
  src/main/java/grep/neogulcoder/domain/study/service/StudySchedulerService.java
  src/main/java/grep/neogulcoder/domain/timevote/dto/response/TimeVotePeriodResponse.java
  src/main/java/grep/neogulcoder/domain/timevote/provider/TimeVoteMessageProvider.java
  src/main/java/grep/neogulcoder/domain/timevote/service/TimeVotePeriodService.java
  src/main/java/grep/neogulcoder/domain/users/service/UserService.java
  src/main/java/grep/neogulcoder/global/auth/oauth/OAuthSuccessHandler.java
  src/main/resources/data.sql
Labels: 🔧 chore

#226 [EA3-134] fix : 누락된 알림 타입 추가
  src/main/java/grep/neogulcoder/domain/alram/type/AlarmType.java
Labels: 🐛 fix

#230 [EA3-163] Fix: 스터디 게시글 업데이트 오류 수정
  src/main/java/grep/neogulcoder/domain/studypost/controller/dto/request/StudyPostUpdateRequest.java
  src/main/java/grep/neogulcoder/domain/studypost/controller/dto/response/CommentInfo.java
Labels: 🐛 fix

#235 [EA3-187]Feature: 알림 전체 조회 엔드포인트 추가 및 읽음 여부 반환 추기
  src/main/java/grep/neogulcoder/domain/alram/controller/AlarmController.java
  src/main/java/grep/neogulcoder/domain/alram/controller/AlarmSpecification.java
  src/main/java/grep/neogulcoder/domain/alram/controller/dto/response/AlarmResponse.java
  src/main/java/grep/neogulcoder/domain/alram/repository/AlarmRepository.java
  src/main/java/grep/neogulcoder/domain/alram/service/AlarmService.java
Labels: ✨ feature

#234 [EA3-188] feature: 내 스터디 신청 목록 조회 응답 필드 추가
  src/main/java/grep/neogulcoder/domain/studyapplication/controller/dto/response/MyApplicationPagingResponse.java
  src/main/java/grep/neogulcoder/domain/studyapplication/controller/dto/response/MyApplicationResponse.java
  src/main/java/grep/neogulcoder/domain/studyapplication/repository/ApplicationQueryRepository.java
  src/main/java/grep/neogulcoder/domain/timevote/repository/TimeVoteQueryRepository.java
Labels: ✨ feature

#237 [EA3-190] Feature: 모집글 목업 데이터 수정 및 조회 전체권한 수정
  src/main/java/grep/neogulcoder/global/config/security/SecurityConfig.java
  src/main/resources/data.sql
Labels: ✨ feature

#239 [EA3-191] refactor: 스터디 연장 반환값 변경
  src/main/java/grep/neogulcoder/domain/study/controller/StudyManagementController.java
  src/main/java/grep/neogulcoder/domain/study/controller/StudyManagementSpecification.java
  src/main/java/grep/neogulcoder/domain/study/service/StudyManagementService.java
Labels: ♻️ refactor

#240 [EA3-68] chore: develop → main 브랜치 머지
  src/main/java/grep/neogulcoder/domain/alram/controller/AlarmController.java
  src/main/java/grep/neogulcoder/domain/alram/controller/AlarmSpecification.java
  src/main/java/grep/neogulcoder/domain/alram/controller/dto/response/AlarmResponse.java
  src/main/java/grep/neogulcoder/domain/alram/repository/AlarmRepository.java
  src/main/java/grep/neogulcoder/domain/alram/service/AlarmService.java
  src/main/java/grep/neogulcoder/domain/alram/type/AlarmType.java
  src/main/java/grep/neogulcoder/domain/recruitment/comment/controller/RecruitmentPostCommentController.java
  src/main/java/grep/neogulcoder/domain/recruitment/comment/controller/RecruitmentPostCommentSpecification.java
  src/main/java/grep/neogulcoder/domain/recruitment/comment/controller/dto/request/RecruitmentCommentSaveRequest.java
  src/main/java/grep/neogulcoder/domain/recruitment/comment/service/RecruitmentPostCommentService.java
  src/main/java/grep/neogulcoder/domain/study/controller/StudyManagementController.java
  src/main/java/grep/neogulcoder/domain/study/controller/StudyManagementSpecification.java
  src/main/java/grep/neogulcoder/domain/study/service/StudyManagementService.java
  src/main/java/grep/neogulcoder/domain/studyapplication/controller/dto/response/MyApplicationPagingResponse.java
  src/main/java/grep/neogulcoder/domain/studyapplication/controller/dto/response/MyApplicationResponse.java
  src/main/java/grep/neogulcoder/domain/studyapplication/repository/ApplicationQueryRepository.java
  src/main/java/grep/neogulcoder/domain/studypost/controller/dto/request/StudyPostUpdateRequest.java
  src/main/java/grep/neogulcoder/domain/studypost/controller/dto/response/CommentInfo.java
  src/main/java/grep/neogulcoder/domain/timevote/TimeVote.java
  src/main/java/grep/neogulcoder/domain/timevote/TimeVotePeriod.java
  src/main/java/grep/neogulcoder/domain/timevote/TimeVoteStat.java
  src/main/java/grep/neogulcoder/domain/timevote/controller/TimeVoteController.java
  src/main/java/grep/neogulcoder/domain/timevote/dto/request/TimeVoteCreateRequest.java
  src/main/java/grep/neogulcoder/domain/timevote/dto/request/TimeVotePeriodCreateRequest.java
  src/main/java/grep/neogulcoder/domain/timevote/dto/request/TimeVoteUpdateRequest.java
  src/main/java/grep/neogulcoder/domain/timevote/dto/response/TimeVotePeriodResponse.java
  src/main/java/grep/neogulcoder/domain/timevote/dto/response/TimeVoteResponse.java
  src/main/java/grep/neogulcoder/domain/timevote/dto/response/TimeVoteStatResponse.java
  src/main/java/grep/neogulcoder/domain/timevote/event/TimeVotePeriodCreatedEvent.java
  src/main/java/grep/neogulcoder/domain/timevote/repository/TimeVotePeriodRepository.java
  src/main/java/grep/neogulcoder/domain/timevote/repository/TimeVoteQueryRepository.java
  src/main/java/grep/neogulcoder/domain/timevote/repository/TimeVoteRepository.java
  src/main/java/grep/neogulcoder/domain/timevote/repository/TimeVoteStatQueryRepository.java
  src/main/java/grep/neogulcoder/domain/timevote/repository/TimeVoteStatRepository.java
  src/main/java/grep/neogulcoder/domain/timevote/service/TimeVotePeriodService.java
  src/main/java/grep/neogulcoder/domain/timevote/service/TimeVoteService.java
  src/main/java/grep/neogulcoder/domain/timevote/service/TimeVoteStatService.java
  src/main/java/grep/neogulcoder/global/config/security/SecurityConfig.java
  src/main/resources/data.sql
Labels: 🔧 chore

#245 [EA3-190] Refactor: 모집글 수정 필드명 수정
  src/main/java/grep/neogulcoder/domain/recruitment/post/controller/dto/request/RecruitmentPostUpdateRequest.java
Labels: ♻️ refactor

#244 [EA3-111] feature : 과거 채팅 응답구조 개선 및 dto 추가
  src/main/java/grep/neogulcoder/domain/groupchat/controller/GroupChatRestController.java
  src/main/java/grep/neogulcoder/domain/groupchat/controller/GroupChatRestSpecification.java
  src/main/java/grep/neogulcoder/domain/groupchat/controller/dto/response/ChatMessagePagingResponse.java
  src/main/java/grep/neogulcoder/domain/groupchat/repository/GroupChatMessageRepository.java
  src/main/java/grep/neogulcoder/domain/groupchat/service/GroupChatService.java
Labels: ✨ feature, ♻️ refactor

#243 Feature: 알람 목록 조회 시 알람 생성 시간 반환 추가
  src/main/java/grep/neogulcoder/domain/alram/controller/dto/response/AlarmResponse.java
  src/main/java/grep/neogulcoder/domain/alram/service/AlarmService.java
Labels: ✨ feature

#248 [EA3-196] feature: 스터디 헤더 조회 필드 추가
  src/main/java/grep/neogulcoder/domain/alram/service/AlarmService.java
  src/main/java/grep/neogulcoder/domain/study/controller/dto/response/StudyHeaderResponse.java
  src/main/java/grep/neogulcoder/domain/study/service/StudyService.java
Labels: ✨ feature

#249 [EA3-68] chore: develop → main 브랜치 머지
  src/main/java/grep/neogulcoder/domain/alram/service/AlarmService.java
  src/main/java/grep/neogulcoder/domain/study/controller/dto/response/StudyHeaderResponse.java
  src/main/java/grep/neogulcoder/domain/study/service/StudyService.java
Labels: 🔧 chore

#250 [EA3-138] Feature: 모집글 댓글 작성시 알림 기능 추가
  src/main/java/grep/neogulcoder/domain/alram/controller/AlarmController.java
  src/main/java/grep/neogulcoder/domain/alram/service/AlarmService.java
  src/main/java/grep/neogulcoder/domain/alram/type/AlarmType.java
  src/main/java/grep/neogulcoder/domain/recruitment/comment/controller/dto/request/RecruitmentCommentSaveRequest.java
  src/main/java/grep/neogulcoder/domain/recruitment/comment/event/RecruitmentPostCommentEvent.java
  src/main/java/grep/neogulcoder/domain/recruitment/comment/event/RecruitmentPostCommentMessageFinder.java
  src/main/java/grep/neogulcoder/domain/recruitment/comment/service/RecruitmentPostCommentService.java
  src/main/java/grep/neogulcoder/domain/recruitment/post/RecruitmentPost.java
  src/main/java/grep/neogulcoder/domain/studypost/comment/event/StudyPostCommentEvent.java
  src/main/java/grep/neogulcoder/domain/studypost/comment/service/StudyPostCommentService.java
  src/test/java/grep/neogulcoder/domain/recruitment/comment/service/RecruitmentPostCommentServiceTest.java
  src/test/java/grep/neogulcoder/global/provider/finder/MessageFinderTest.java
Labels: ✨ feature

#251 [EA3-163] Feature: 스터디 게시글 댓글 작성시 알림 추가
  src/main/java/grep/neogulcoder/domain/alram/service/AlarmService.java
  src/main/java/grep/neogulcoder/domain/alram/type/AlarmType.java
  src/main/java/grep/neogulcoder/domain/alram/type/DomainType.java
  src/main/java/grep/neogulcoder/domain/studypost/StudyPost.java
  src/main/java/grep/neogulcoder/domain/studypost/comment/event/StudyPostCommentEvent.java
  src/main/java/grep/neogulcoder/domain/studypost/comment/event/StudyPostCommentMessageFinder.java
  src/main/java/grep/neogulcoder/domain/studypost/comment/service/StudyPostCommentService.java
Labels: ✨ feature

#252 [EA3-68] chore: develop → main 브랜치 머지
  src/main/java/grep/neogulcoder/domain/alram/controller/AlarmController.java
  src/main/java/grep/neogulcoder/domain/alram/service/AlarmService.java
  src/main/java/grep/neogulcoder/domain/alram/type/AlarmType.java
  src/main/java/grep/neogulcoder/domain/alram/type/DomainType.java
  src/main/java/grep/neogulcoder/domain/recruitment/comment/controller/dto/request/RecruitmentCommentSaveRequest.java
  src/main/java/grep/neogulcoder/domain/recruitment/comment/event/RecruitmentPostCommentEvent.java
  src/main/java/grep/neogulcoder/domain/recruitment/comment/event/RecruitmentPostCommentMessageFinder.java
  src/main/java/grep/neogulcoder/domain/recruitment/comment/service/RecruitmentPostCommentService.java
  src/main/java/grep/neogulcoder/domain/recruitment/post/RecruitmentPost.java
  src/main/java/grep/neogulcoder/domain/studypost/StudyPost.java
  src/main/java/grep/neogulcoder/domain/studypost/comment/event/StudyPostCommentEvent.java
  src/main/java/grep/neogulcoder/domain/studypost/comment/event/StudyPostCommentMessageFinder.java
  src/main/java/grep/neogulcoder/domain/studypost/comment/service/StudyPostCommentService.java
  src/test/java/grep/neogulcoder/domain/recruitment/comment/service/RecruitmentPostCommentServiceTest.java
  src/test/java/grep/neogulcoder/global/provider/finder/MessageFinderTest.java
Labels: 🔧 chore

#253 [EA3-138] feature: 모집글 조회시 모집글 작성자의 식별자, 이미지 추가
  src/main/java/grep/neogulcoder/domain/recruitment/post/controller/dto/response/RecruitmentPostWithStudyInfo.java
  src/main/java/grep/neogulcoder/domain/recruitment/post/repository/RecruitmentPostQueryRepository.java
Labels: ✨ feature

#258 [EA3-68] chore: develop → main 브랜치 머지
  src/main/java/grep/neogulcoder/domain/recruitment/post/controller/dto/response/RecruitmentPostWithStudyInfo.java
  src/main/java/grep/neogulcoder/domain/recruitment/post/repository/RecruitmentPostQueryRepository.java
Labels: 🔧 chore

#256 [EA3-195] refactor: 스터디 리팩터링 및 문제 해결
  src/main/java/grep/neogulcoder/domain/study/Study.java
  src/main/java/grep/neogulcoder/domain/study/repository/StudyMemberQueryRepository.java
  src/main/java/grep/neogulcoder/domain/study/service/StudyManagementService.java
  src/main/java/grep/neogulcoder/domain/study/service/StudyManagementServiceFacade.java
Labels: ♻️ refactor

#257 [EA3-197] refactor: 스터디 정보 조회 권한 수정
  src/main/java/grep/neogulcoder/domain/study/service/StudyService.java
Labels: ♻️ refactor

#259 [EA3-198] refactor: 스터디 목록 조회 스터디장 닉네임 수정
  src/main/java/grep/neogulcoder/domain/study/repository/StudyQueryRepository.java
Labels: ♻️ refactor

#260 [EA3-183] refactor : 모임 일정 조율 관련 검증 로직 및 예외 응답 구조 리팩토링 (강사 피드백 반영)
  src/main/java/grep/neogulcoder/domain/timevote/TimeVote.java
  src/main/java/grep/neogulcoder/domain/timevote/TimeVotePeriod.java
  src/main/java/grep/neogulcoder/domain/timevote/TimeVoteStat.java
  src/main/java/grep/neogulcoder/domain/timevote/context/TimeVoteContext.java
  src/main/java/grep/neogulcoder/domain/timevote/controller/TimeVoteController.java
  src/main/java/grep/neogulcoder/domain/timevote/controller/TimeVoteSpecification.java
  src/main/java/grep/neogulcoder/domain/timevote/dto/request/TimeVoteCreateRequest.java
  src/main/java/grep/neogulcoder/domain/timevote/dto/request/TimeVotePeriodCreateRequest.java
  src/main/java/grep/neogulcoder/domain/timevote/dto/request/TimeVoteUpdateRequest.java
  src/main/java/grep/neogulcoder/domain/timevote/dto/response/TimeVotePeriodResponse.java
  src/main/java/grep/neogulcoder/domain/timevote/exception/code/TimeVoteErrorCode.java
  src/main/java/grep/neogulcoder/domain/timevote/service/TimeVoteMapper.java
  src/main/java/grep/neogulcoder/domain/timevote/service/TimeVotePeriodService.java
  src/main/java/grep/neogulcoder/domain/timevote/service/TimeVoteService.java
  src/main/java/grep/neogulcoder/domain/timevote/service/TimeVoteStatService.java
  src/main/java/grep/neogulcoder/domain/timevote/service/period/TimeVotePeriodService.java
  src/main/java/grep/neogulcoder/domain/timevote/service/period/TimeVotePeriodValidator.java
  src/main/java/grep/neogulcoder/domain/timevote/service/stat/TimeVoteStatService.java
  src/main/java/grep/neogulcoder/domain/timevote/service/stat/TimeVoteStatValidator.java
  src/main/java/grep/neogulcoder/domain/timevote/service/vote/TimeVoteService.java
  src/main/java/grep/neogulcoder/domain/timevote/service/vote/TimeVoteValidator.java
  src/main/java/grep/neogulcoder/global/exception/advice/WebExceptionAdvice.java
  src/main/java/grep/neogulcoder/global/response/ApiResponse.java
Labels: ♻️ refactor, 🔧 chore

#265 Feature: 배포 후 OAuth 리다이렉트 Url 수정
  src/main/java/grep/neogulcoder/global/auth/oauth/OAuthSuccessHandler.java
Labels: ✨ feature

#271 [EA3-201]Fix: 초대 수락/거절 시 받은 사람 ID와 알림 ID를 통해 찾도록 변경
  src/main/java/grep/neogulcoder/domain/alram/controller/AlarmController.java
  src/main/java/grep/neogulcoder/domain/alram/exception/code/AlarmErrorCode.java
  src/main/java/grep/neogulcoder/domain/alram/repository/AlarmRepository.java
  src/main/java/grep/neogulcoder/domain/alram/service/AlarmService.java
Labels: 🐛 fix, ✨ feature

#273 [EA3-195] refactor: 스터디 로직 리팩터링
  src/main/java/grep/neogulcoder/domain/alram/service/AlarmService.java
  src/main/java/grep/neogulcoder/domain/recruitment/post/repository/RecruitmentPostRepository.java
  src/main/java/grep/neogulcoder/domain/study/Study.java
  src/main/java/grep/neogulcoder/domain/study/StudyMember.java
  src/main/java/grep/neogulcoder/domain/study/controller/StudyController.java
  src/main/java/grep/neogulcoder/domain/study/controller/StudyManagementController.java
  src/main/java/grep/neogulcoder/domain/study/controller/StudyManagementSpecification.java
  src/main/java/grep/neogulcoder/domain/study/controller/StudySpecification.java
  src/main/java/grep/neogulcoder/domain/study/controller/dto/request/ExtendStudyRequest.java
  src/main/java/grep/neogulcoder/domain/study/controller/dto/request/StudyCreateRequest.java
  src/main/java/grep/neogulcoder/domain/study/controller/dto/request/StudyUpdateRequest.java
  src/main/java/grep/neogulcoder/domain/study/controller/dto/response/ExtendParticipationResponse.java
  src/main/java/grep/neogulcoder/domain/study/controller/dto/response/StudyExtensionResponse.java
  src/main/java/grep/neogulcoder/domain/study/controller/dto/response/StudyHeaderResponse.java
  src/main/java/grep/neogulcoder/domain/study/controller/dto/response/StudyImageResponse.java
  src/main/java/grep/neogulcoder/domain/study/controller/dto/response/StudyInfoResponse.java
  src/main/java/grep/neogulcoder/domain/study/controller/dto/response/StudyItemPagingResponse.java
  src/main/java/grep/neogulcoder/domain/study/controller/dto/response/StudyItemResponse.java
  src/main/java/grep/neogulcoder/domain/study/controller/dto/response/StudyMemberInfoResponse.java
  src/main/java/grep/neogulcoder/domain/study/controller/dto/response/StudyMemberResponse.java
  src/main/java/grep/neogulcoder/domain/study/controller/dto/response/StudyMyContentResponse.java
  src/main/java/grep/neogulcoder/domain/study/controller/dto/response/StudyResponse.java
  src/main/java/grep/neogulcoder/domain/study/enums/StudyType.java
  src/main/java/grep/neogulcoder/domain/study/exception/code/StudyErrorCode.java
  src/main/java/grep/neogulcoder/domain/study/provider/StudyExtendMessageProvider.java
  src/main/java/grep/neogulcoder/domain/study/provider/StudyExtensionReminderMessageProvider.java
  src/main/java/grep/neogulcoder/domain/study/repository/StudyMemberQueryRepository.java
  src/main/java/grep/neogulcoder/domain/study/repository/StudyMemberRepository.java
  src/main/java/grep/neogulcoder/domain/study/repository/StudyQueryRepository.java
  src/main/java/grep/neogulcoder/domain/study/scheduler/StudyScheduler.java
  src/main/java/grep/neogulcoder/domain/study/service/StudyManagementService.java
  src/main/java/grep/neogulcoder/domain/study/service/StudyManagementServiceFacade.java
  src/main/java/grep/neogulcoder/domain/study/service/StudyService.java
Labels: ♻️ refactor

#274 [EA3-68] chore: develop → main 브랜치 머지
  src/main/java/grep/neogulcoder/domain/alram/controller/AlarmController.java
  src/main/java/grep/neogulcoder/domain/alram/exception/code/AlarmErrorCode.java
  src/main/java/grep/neogulcoder/domain/alram/repository/AlarmRepository.java
  src/main/java/grep/neogulcoder/domain/alram/service/AlarmService.java
  src/main/java/grep/neogulcoder/domain/recruitment/post/repository/RecruitmentPostRepository.java
  src/main/java/grep/neogulcoder/domain/study/Study.java
  src/main/java/grep/neogulcoder/domain/study/StudyMember.java
  src/main/java/grep/neogulcoder/domain/study/controller/StudyController.java
  src/main/java/grep/neogulcoder/domain/study/controller/StudyManagementController.java
  src/main/java/grep/neogulcoder/domain/study/controller/StudyManagementSpecification.java
  src/main/java/grep/neogulcoder/domain/study/controller/StudySpecification.java
  src/main/java/grep/neogulcoder/domain/study/controller/dto/request/ExtendStudyRequest.java
  src/main/java/grep/neogulcoder/domain/study/controller/dto/request/StudyCreateRequest.java
  src/main/java/grep/neogulcoder/domain/study/controller/dto/request/StudyUpdateRequest.java
  src/main/java/grep/neogulcoder/domain/study/controller/dto/response/ExtendParticipationResponse.java
  src/main/java/grep/neogulcoder/domain/study/controller/dto/response/StudyExtensionResponse.java
  src/main/java/grep/neogulcoder/domain/study/controller/dto/response/StudyHeaderResponse.java
  src/main/java/grep/neogulcoder/domain/study/controller/dto/response/StudyImageResponse.java
  src/main/java/grep/neogulcoder/domain/study/controller/dto/response/StudyInfoResponse.java
  src/main/java/grep/neogulcoder/domain/study/controller/dto/response/StudyItemPagingResponse.java
  src/main/java/grep/neogulcoder/domain/study/controller/dto/response/StudyItemResponse.java
  src/main/java/grep/neogulcoder/domain/study/controller/dto/response/StudyMemberInfoResponse.java
  src/main/java/grep/neogulcoder/domain/study/controller/dto/response/StudyMemberResponse.java
  src/main/java/grep/neogulcoder/domain/study/controller/dto/response/StudyMyContentResponse.java
  src/main/java/grep/neogulcoder/domain/study/controller/dto/response/StudyResponse.java
  src/main/java/grep/neogulcoder/domain/study/enums/StudyType.java
  src/main/java/grep/neogulcoder/domain/study/exception/code/StudyErrorCode.java
  src/main/java/grep/neogulcoder/domain/study/provider/StudyExtendMessageProvider.java
  src/main/java/grep/neogulcoder/domain/study/provider/StudyExtensionReminderMessageProvider.java
  src/main/java/grep/neogulcoder/domain/study/repository/StudyMemberQueryRepository.java
  src/main/java/grep/neogulcoder/domain/study/repository/StudyMemberRepository.java
  src/main/java/grep/neogulcoder/domain/study/repository/StudyQueryRepository.java
  src/main/java/grep/neogulcoder/domain/study/scheduler/StudyScheduler.java
  src/main/java/grep/neogulcoder/domain/study/service/StudyManagementService.java
  src/main/java/grep/neogulcoder/domain/study/service/StudyManagementServiceFacade.java
  src/main/java/grep/neogulcoder/domain/study/service/StudyService.java
  src/main/java/grep/neogulcoder/domain/timevote/TimeVoteStat.java
  src/main/java/grep/neogulcoder/domain/timevote/exception/code/TimeVoteErrorCode.java
  src/main/java/grep/neogulcoder/domain/timevote/repository/TimeVotePeriodRepository.java
  src/main/java/grep/neogulcoder/domain/timevote/repository/TimeVoteQueryRepository.java
  src/main/java/grep/neogulcoder/domain/timevote/repository/TimeVoteRepository.java
  src/main/java/grep/neogulcoder/domain/timevote/repository/TimeVoteStatQueryRepository.java
  src/main/java/grep/neogulcoder/domain/timevote/repository/TimeVoteStatRepository.java
  src/main/java/grep/neogulcoder/domain/timevote/service/TimeVoteMapper.java
  src/main/java/grep/neogulcoder/domain/timevote/service/period/TimeVotePeriodService.java
  src/main/java/grep/neogulcoder/domain/timevote/service/stat/TimeVoteStatService.java
  src/main/java/grep/neogulcoder/domain/timevote/service/stat/TimeVoteStatValidator.java
  src/main/java/grep/neogulcoder/domain/timevote/service/vote/TimeVoteCleanupScheduler.java
  src/main/java/grep/neogulcoder/domain/timevote/service/vote/TimeVoteService.java
  src/main/java/grep/neogulcoder/domain/timevote/service/vote/TimeVoteValidator.java
  src/main/resources/data.sql
  src/main/resources/schema.sql
Labels: 🔧 chore

#275 [EA3-138] feature: 모집글 조회 시큐리티 설정 추가
  src/main/java/grep/neogulcoder/global/config/security/SecurityConfig.java
Labels: ✨ feature

#277 [EA3-183] chore : data.sql 스터디 멤버 번호 수정(test 계정)
  src/main/resources/data.sql
Labels: 🔧 chore

#276 [EA3-156] feature: 주관식 리뷰 작성시 빈값 허용 방지 추가
  src/main/java/grep/neogulcoder/domain/review/controller/dto/request/ReviewSaveRequest.java
Labels: ✨ feature

#280 [EA3-200] refactor: 스터디 신청 로직 리팩터링
  src/main/java/grep/neogulcoder/domain/study/Study.java
  src/main/java/grep/neogulcoder/domain/study/service/StudyService.java
  src/main/java/grep/neogulcoder/domain/studyapplication/controller/ApplicationController.java
  src/main/java/grep/neogulcoder/domain/studyapplication/controller/ApplicationSpecification.java
  src/main/java/grep/neogulcoder/domain/studyapplication/controller/dto/response/MyApplicationPagingResponse.java
  src/main/java/grep/neogulcoder/domain/studyapplication/controller/dto/response/MyApplicationResponse.java
  src/main/java/grep/neogulcoder/domain/studyapplication/controller/dto/response/ReceivedApplicationPagingResponse.java
  src/main/java/grep/neogulcoder/domain/studyapplication/controller/dto/response/ReceivedApplicationResponse.java
  src/main/java/grep/neogulcoder/domain/studyapplication/provider/ApplicationApprovedMessageProvider.java
  src/main/java/grep/neogulcoder/domain/studyapplication/provider/ApplicationMessageProvider.java
  src/main/java/grep/neogulcoder/domain/studyapplication/provider/ApplicationRejectedMessageProvider.java
  src/main/java/grep/neogulcoder/domain/studyapplication/repository/ApplicationQueryRepository.java
  src/main/java/grep/neogulcoder/domain/studyapplication/service/ApplicationService.java
Labels: ♻️ refactor

#285 [EA3-206] Refactor: 응답값에 대한 변경
  src/main/java/grep/neogulcoder/domain/admin/controller/AdminController.java
  src/main/java/grep/neogulcoder/domain/admin/controller/AdminSpecification.java
  src/main/java/grep/neogulcoder/domain/alram/controller/AlarmController.java
  src/main/java/grep/neogulcoder/domain/alram/controller/AlarmSpecification.java
  src/main/java/grep/neogulcoder/domain/prtemplate/controller/PrTemplateController.java
  src/main/java/grep/neogulcoder/domain/prtemplate/controller/PrTemplateSpecification.java
  src/main/java/grep/neogulcoder/domain/users/controller/UserController.java
  src/main/java/grep/neogulcoder/domain/users/controller/UserSpecification.java
Labels: ♻️ refactor

#291 [EA3-207] refactor: 알림 도메인 타입 검증 에러코드 수정
  src/main/java/grep/neogulcoder/domain/alram/exception/code/AlarmErrorCode.java
  src/main/java/grep/neogulcoder/domain/alram/service/AlarmService.java
  src/main/java/grep/neogulcoder/domain/alram/type/AlarmType.java
  src/main/java/grep/neogulcoder/domain/study/provider/InviteMessageProvider.java
  src/main/java/grep/neogulcoder/domain/study/provider/StudyExtendMessageProvider.java
  src/main/java/grep/neogulcoder/domain/study/provider/StudyExtensionReminderMessageProvider.java
  src/main/java/grep/neogulcoder/domain/studyapplication/provider/ApplicationApprovedMessageProvider.java
  src/main/java/grep/neogulcoder/domain/studyapplication/provider/ApplicationMessageProvider.java
  src/main/java/grep/neogulcoder/domain/studyapplication/provider/ApplicationRejectedMessageProvider.java
  src/main/java/grep/neogulcoder/domain/timevote/provider/TimeVoteMessageProvider.java
  src/main/java/grep/neogulcoder/global/provider/finder/MessageFinder.java
Labels: ♻️ refactor

#294 [EA3-207] fix: sql 알림 타입 수정
  src/main/resources/data.sql
Labels: 🐛 fix

#297 [EA3-183] chore : JWT 의존성 수정 및 추가
  build.gradle
Labels: 🔧 chore

#298 Fix: 스터디에 초대 시 RequestParam 부재로 인한 에러 해결
  src/main/java/grep/neogulcoder/domain/study/controller/StudyManagementController.java
Labels: 🐛 fix

#299 [EA3-68] chore: develop → main 브랜치 머지
  build.gradle
  src/main/java/grep/neogulcoder/domain/recruitment/RecruitmentErrorCode.java
  src/main/java/grep/neogulcoder/domain/recruitment/post/controller/RecruitmentPostSaveController.java
  src/main/java/grep/neogulcoder/domain/recruitment/post/controller/dto/request/save/RecruitmentPostCreateRequest.java
  src/main/java/grep/neogulcoder/domain/recruitment/post/service/RecruitmentPostSaveService.java
  src/main/java/grep/neogulcoder/domain/study/Study.java
  src/main/java/grep/neogulcoder/domain/study/controller/StudyManagementController.java
  src/main/java/grep/neogulcoder/domain/study/repository/StudyMemberQueryRepository.java
Labels: 🔧 chore

#301 [EA3-195] refactor: 스터디 종료 로직 쿼리 수정
  src/main/java/grep/neogulcoder/domain/study/service/StudySchedulerService.java
Labels: ♻️ refactor

#300 [EA3-209] refactor: 모집글 저장시 모집 기간 수정
  src/main/java/grep/neogulcoder/domain/recruitment/RecruitmentErrorCode.java
  src/main/java/grep/neogulcoder/domain/recruitment/post/controller/RecruitmentPostSaveController.java
  src/main/java/grep/neogulcoder/domain/recruitment/post/controller/dto/request/save/RecruitmentPostCreateRequest.java
  src/main/java/grep/neogulcoder/domain/recruitment/post/service/RecruitmentPostSaveService.java
  src/main/java/grep/neogulcoder/domain/study/Study.java
Labels: ♻️ refactor

#302 [EA3-68] chore: develop → main 브랜치 머지
  src/main/java/grep/neogulcoder/domain/recruitment/RecruitmentErrorCode.java
  src/main/java/grep/neogulcoder/domain/recruitment/post/controller/RecruitmentPostSaveController.java
  src/main/java/grep/neogulcoder/domain/recruitment/post/controller/dto/request/save/RecruitmentPostCreateRequest.java
  src/main/java/grep/neogulcoder/domain/recruitment/post/service/RecruitmentPostSaveService.java
  src/main/java/grep/neogulcoder/domain/study/Study.java
  src/main/java/grep/neogulcoder/domain/study/service/StudySchedulerService.java
Labels: 🔧 chore

#303 [EA3-195] refactor: 스터디 종료 로직 수정 및 쿼리 수정
  src/main/java/grep/neogulcoder/domain/buddy/entity/BuddyEnergy.java
  src/main/java/grep/neogulcoder/domain/buddy/repository/BuddyEnergyRepository.java
  src/main/java/grep/neogulcoder/domain/buddy/service/BuddyEnergyService.java
  src/main/java/grep/neogulcoder/domain/study/repository/StudyMemberQueryRepository.java
  src/main/java/grep/neogulcoder/domain/study/repository/StudyMemberRepository.java
  src/main/java/grep/neogulcoder/domain/study/service/StudyManagementService.java
  src/main/java/grep/neogulcoder/domain/study/service/StudySchedulerService.java
  src/main/java/grep/neogulcoder/domain/study/service/StudyService.java
Labels: ♻️ refactor

#305 [EA3-209] Refactor: 모집글, 스터디 게시글 검색 수정
  src/main/java/grep/neogulcoder/domain/recruitment/post/repository/RecruitmentPostQueryRepository.java
  src/main/java/grep/neogulcoder/domain/studypost/repository/StudyPostQueryRepository.java
Labels: ♻️ refactor

#306 Fix: 회원 탈퇴 시 비밀번호 확인을 체크하지 않던 문제 해결
  src/main/java/grep/neogulcoder/domain/users/controller/UserController.java
  src/main/java/grep/neogulcoder/domain/users/controller/dto/request/PasswordRequest.java
  src/main/java/grep/neogulcoder/domain/users/service/UserService.java
Labels: 🐛 fix

#308 fix: Study currentCount 증감 오류 해결
  src/main/java/grep/neogulcoder/domain/alram/service/AlarmService.java
  src/main/java/grep/neogulcoder/domain/study/controller/StudyController.java
  src/main/java/grep/neogulcoder/domain/study/service/StudyManagementService.java
  src/main/java/grep/neogulcoder/domain/study/service/StudyManagementServiceFacade.java
  src/main/java/grep/neogulcoder/domain/study/service/StudyMemberCountService.java
  src/main/java/grep/neogulcoder/domain/study/service/StudyService.java
  src/main/java/grep/neogulcoder/domain/studyapplication/service/ApplicationService.java
Labels: 🐛 fix

#311 refactor: 스터디 게시글 검색 조회 수정
  src/main/java/grep/neogulcoder/domain/studypost/repository/StudyPostQueryRepository.java
Labels: ♻️ refactor
